"""Registry of every user-tunable LemonCrow setting.

Each :class:`SettingSpec` binds a dotted CLI key (used by ``lc settings
show``/``set``) to the environment variable that actually drives runtime
behavior. This is the single source of truth consumed by
``lemoncrow.core.settings`` (persistence + env seeding) and the ``lc
settings`` CLI group.

Scope: this covers env vars read by Python code under ``src/`` — i.e. knobs
that can actually change behavior in a running LemonCrow process. Shell-only
install-script variables (``integrations/*/install.sh``) are out of scope
since they run before any Python process exists to seed them.

``default`` is informational only (shown by ``settings show`` when nothing is
persisted); the real runtime code paths already carry their own fallback and
are unaffected by what's recorded here. ``None`` means "LemonCrow picks an
internal default; see source for the exact value."

``settable=False`` marks values that are read-only through this surface —
either because they are generated per-run (swarm child ids, result paths) or
because they are the bootstrap knobs (``LEMONCROW_ROOT`` and friends) that this
very file's location depends on, so persisting them here would be circular.
They still show up in ``lc settings show`` for discoverability.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Literal

SettingType = Literal["bool", "int", "float", "str"]


@dataclass(frozen=True)
class SettingSpec:
    key: str
    env_var: str | None
    type: SettingType
    default: Any
    category: str
    description: str
    settable: bool = True


SETTINGS: list[SettingSpec] = [
    # -- plugin: Claude plugin runtime toggles (persisted only; no env var) --
    SettingSpec(
        "attribution",
        None,
        "bool",
        True,
        "plugin",
        "Append the LemonCrow co-author trailer to commits/PRs made during a session.",
    ),
    SettingSpec(
        "statusLine",
        None,
        "bool",
        True,
        "plugin",
        "Install the LemonCrow statusline segment into the host's settings.json.",
    ),
    SettingSpec("statusLineSession", None, "bool", True, "plugin", "Show this-session savings on the statusline."),
    SettingSpec("statusLineLifetime", None, "bool", True, "plugin", "Show lifetime savings on the statusline."),
    SettingSpec("statusLineTips", None, "bool", True, "plugin", "Rotate tip/message text into the statusline."),
    SettingSpec(
        "statusLineShare", None, "bool", True, "plugin", "Include the share/referral prompt in statusline rotation."
    ),
    SettingSpec(
        "spinnerVerbs",
        None,
        "bool",
        True,
        "plugin",
        "Replace the host's spinner verbs with LemonCrow's set (Reasoning, Searching, ...).",
    ),
    SettingSpec(
        "alwaysLoadTools",
        None,
        "bool",
        True,
        "plugin",
        "Mark the LemonCrow MCP server alwaysLoad so its tools are available immediately.",
    ),
    SettingSpec(
        "nudge.stale_days",
        "LEMONCROW_STALE_NUDGE_DAYS",
        "int",
        7,
        "plugin",
        "Days an installed OPTIONAL (non-default) agent/skill can go unused before a staleness nudge "
        "suggests removing it.",
    ),
    # -- service: local HTTP service (lcd) --
    SettingSpec(
        "service.enabled",
        "LEMONCROW_SERVICE_ENABLED",
        "bool",
        False,
        "service",
        "Enable the local LemonCrow HTTP service.",
    ),
    SettingSpec(
        "service.require_auth",
        "LEMONCROW_REQUIRE_AUTH",
        "bool",
        None,
        "service",
        "Force Bearer-auth on/off for the service (default: on unless bound to loopback).",
    ),
    SettingSpec(
        "service.api_key",
        "LEMONCROW_API_KEY",
        "str",
        "",
        "service",
        "Bearer API key required by the service when auth is enforced.",
    ),
    SettingSpec(
        "service.host",
        "LEMONCROW_SERVICE_HOST",
        "str",
        "127.0.0.1",
        "service",
        "Bind host for the local LemonCrow HTTP service.",
    ),
    SettingSpec(
        "service.port",
        "LEMONCROW_SERVICE_PORT",
        "int",
        8787,
        "service",
        "Bind port for the local LemonCrow HTTP service.",
    ),
    SettingSpec(
        "service.storage_backend",
        "LEMONCROW_STORAGE_BACKEND",
        "str",
        "sqlite",
        "service",
        "Storage backend for the service (sqlite or postgres).",
    ),
    SettingSpec(
        "service.database_url",
        "LEMONCROW_DATABASE_URL",
        "str",
        "",
        "service",
        "Connection URL when storage_backend=postgres.",
    ),
    SettingSpec(
        "service.lessons_root",
        "LEMONCROW_LESSONS_ROOT",
        "str",
        "",
        "service",
        "Project-local lessons root (usually ./.lemoncrow/lessons).",
    ),
    SettingSpec(
        "service.url",
        "LEMONCROW_SERVICE_URL",
        "str",
        "http://localhost:8787",
        "service",
        "Base URL clients use to reach the LemonCrow service (remote_client).",
    ),
    SettingSpec(
        "service.app_url",
        "LEMONCROW_APP_URL",
        "str",
        "https://127.0.0.1:8787",
        "service",
        "Base URL of the LemonCrow web app used for login/share links.",
    ),
    SettingSpec(
        "service.gateway_token",
        "LEMONCROW_GATEWAY_TOKEN",
        "str",
        "",
        "service",
        "Bearer token required by the OpenAI-compatible gateway (serve-openai).",
    ),
    SettingSpec(
        "service.frontend_dir",
        "LEMONCROW_FRONTEND_DIR",
        "str",
        "",
        "service",
        "Override directory the daemon serves the dashboard frontend from.",
    ),
    SettingSpec(
        "service.port_legacy",
        "LEMONCROW_PORT",
        "int",
        8787,
        "service",
        "Legacy port override consulted by the daemon's root_url banner.",
    ),
    SettingSpec(
        "service.host_legacy",
        "LEMONCROW_HOST",
        "str",
        "127.0.0.1",
        "service",
        "Legacy bind-host override consulted by lcd's --host default.",
    ),
    SettingSpec(
        "service.web_port",
        "LEMONCROW_WEB_PORT",
        "int",
        7700,
        "service",
        "Port used to build local share links (lc share).",
    ),
    SettingSpec(
        "service.code_warm",
        "LEMONCROW_SERVICE_CODE_WARM",
        "bool",
        True,
        "service",
        "Warm the code index on service startup.",
    ),
    SettingSpec(
        "service.job_lease_seconds",
        "LEMONCROW_JOB_LEASE_SECONDS",
        "int",
        None,
        "service",
        "Lease duration (seconds) a background worker holds a claimed job before it's reclaimable.",
    ),
    # -- storage: vector/embedding storage backends --
    SettingSpec(
        "storage.embedding_dim",
        "LEMONCROW_EMBEDDING_DIM",
        "int",
        1536,
        "storage",
        "Vector dimensionality for the Postgres pgvector store.",
    ),
    SettingSpec(
        "storage.embedding_model",
        "LEMONCROW_EMBEDDING_MODEL",
        "str",
        "text-embedding-3-small",
        "storage",
        "Embedding model id used by the vector store.",
    ),
    SettingSpec(
        "storage.embedding_provider",
        "LEMONCROW_EMBEDDING_PROVIDER",
        "str",
        "local",
        "storage",
        "Embedding provider for the vector store (local or openai).",
    ),
    SettingSpec(
        "storage.vector_search_enabled",
        "LEMONCROW_VECTOR_SEARCH_ENABLED",
        "bool",
        False,
        "storage",
        "Enable pgvector-backed semantic search in the Postgres store.",
    ),
    # -- retrieval: code_search / explore ranking and channel tuning --
    SettingSpec(
        "retrieval.additional_dirs",
        "LEMONCROW_ADDITIONAL_DIRS",
        "str",
        "",
        "retrieval",
        "Comma-separated extra directories to include in code search/indexing beyond the workspace root.",
    ),
    SettingSpec(
        "retrieval.ann_cache_limit",
        "LEMONCROW_ANN_CACHE_LIMIT",
        "int",
        200000,
        "retrieval",
        "Max entries kept in the approximate-nearest-neighbor symbol cache.",
    ),
    SettingSpec(
        "retrieval.ann_cache_max_mb",
        "LEMONCROW_ANN_CACHE_MAX_MB",
        "int",
        512,
        "retrieval",
        "Memory ceiling (MB) for the ANN symbol cache.",
    ),
    SettingSpec(
        "retrieval.ann_retrieval",
        "LEMONCROW_ANN_RETRIEVAL",
        "bool",
        False,
        "retrieval",
        "Enable approximate-nearest-neighbor retrieval for code search.",
    ),
    SettingSpec(
        "retrieval.blas_threads",
        "LEMONCROW_BLAS_THREADS",
        "int",
        4,
        "retrieval",
        "Thread cap passed to BLAS-backed numeric libraries during ANN indexing.",
    ),
    SettingSpec(
        "retrieval.codesearch_outline",
        "LEMONCROW_CODESEARCH_OUTLINE",
        "bool",
        False,
        "retrieval",
        "Render code_search results as outlines instead of verbatim source.",
    ),
    SettingSpec(
        "retrieval.codesearch_outline_max_chars",
        "LEMONCROW_CODESEARCH_OUTLINE_MAX_CHARS",
        "int",
        800,
        "retrieval",
        "Max characters per file section when outline rendering is enabled.",
    ),
    SettingSpec(
        "retrieval.codesearch_top2_max_chars",
        "LEMONCROW_CODESEARCH_TOP2_MAX_CHARS",
        "int",
        8000,
        "retrieval",
        "Cap on kept top-2 include_source sections in outline mode (head + pointer beyond).",
    ),
    SettingSpec(
        "retrieval.context_dedup",
        "LEMONCROW_CONTEXT_DEDUP",
        "bool",
        True,
        "retrieval",
        "Deduplicate repeated tool output already seen this session.",
    ),
    SettingSpec(
        "retrieval.explore_parallel",
        "LEMONCROW_EXPLORE_PARALLEL",
        "bool",
        True,
        "retrieval",
        "Run explore/code_search channels (lexical/semantic/graph) in parallel.",
    ),
    SettingSpec(
        "retrieval.explore_reranker_enabled",
        "LEMONCROW_EXPLORE_RERANKER_ENABLED",
        "bool",
        True,
        "retrieval",
        "Rerank explore/code_search candidates with the reranker model.",
    ),
    SettingSpec(
        "retrieval.explore_reranker_model",
        "LEMONCROW_EXPLORE_RERANKER_MODEL",
        "str",
        None,
        "retrieval",
        "Override the reranker model used for explore/code_search.",
    ),
    SettingSpec(
        "retrieval.explore_lexical",
        "LEMONCROW_EXPLORE_LEXICAL",
        "bool",
        True,
        "retrieval",
        "Include the FTS5 lexical channel in explore/code_search (set to 0 for pure-zoekt/semantic eval).",
    ),
    SettingSpec(
        "retrieval.explore_semantic",
        "LEMONCROW_EXPLORE_SEMANTIC",
        "bool",
        True,
        "retrieval",
        "Include the semantic/embedding channel in explore/code_search.",
    ),
    SettingSpec(
        "retrieval.explore_skeleton",
        "LEMONCROW_EXPLORE_SKELETON",
        "str",
        None,
        "retrieval",
        "Override the skeleton/outline projection mode used by explore.",
    ),
    SettingSpec(
        "retrieval.fusion_weight_lexical",
        "LEMONCROW_FUSION_WEIGHT_LEXICAL",
        "float",
        None,
        "retrieval",
        "Fusion weight for the lexical channel when combining search rankings.",
    ),
    SettingSpec(
        "retrieval.fusion_weight_semantic",
        "LEMONCROW_FUSION_WEIGHT_SEMANTIC",
        "float",
        None,
        "retrieval",
        "Fusion weight for the semantic channel when combining search rankings.",
    ),
    SettingSpec(
        "retrieval.fusion_weight_graph",
        "LEMONCROW_FUSION_WEIGHT_GRAPH",
        "float",
        None,
        "retrieval",
        "Fusion weight for the call-graph channel when combining search rankings.",
    ),
    SettingSpec(
        "retrieval.rerank",
        "LEMONCROW_RERANK",
        "bool",
        False,
        "retrieval",
        "Force reranking of selected files for large result sets.",
    ),
    SettingSpec(
        "retrieval.search_breaker_threshold",
        "LEMONCROW_SEARCH_BREAKER_THRESHOLD",
        "float",
        None,
        "retrieval",
        "Verdict-score threshold below which the search circuit breaker trips.",
    ),
    SettingSpec(
        "retrieval.search_cascade_on_empty",
        "LEMONCROW_SEARCH_CASCADE_ON_EMPTY",
        "bool",
        True,
        "retrieval",
        "Cascade to a broader search strategy when the primary channel returns nothing.",
    ),
    SettingSpec(
        "retrieval.search_channel_deadline_s",
        "LEMONCROW_SEARCH_CHANNEL_DEADLINE_S",
        "float",
        2.5,
        "retrieval",
        "Per-channel deadline (seconds) for parallel search channels.",
    ),
    SettingSpec(
        "retrieval.search_reformulation_threshold",
        "LEMONCROW_SEARCH_REFORMULATION_THRESHOLD",
        "float",
        None,
        "retrieval",
        "Verdict-score threshold below which LemonCrow reformulates the query.",
    ),
    SettingSpec(
        "retrieval.self_supervised_training",
        "LEMONCROW_SELF_SUPERVISED_TRAINING",
        "bool",
        False,
        "retrieval",
        "Log self-supervised training signals from explore/rerank outcomes.",
    ),
    SettingSpec(
        "retrieval.semantic_min_score",
        "LEMONCROW_SEMANTIC_MIN_SCORE",
        "float",
        0.35,
        "retrieval",
        "Minimum similarity score for a semantic search hit to be kept.",
    ),
    SettingSpec(
        "retrieval.semantic_mode",
        "LEMONCROW_SEMANTIC_MODE",
        "str",
        "auto",
        "retrieval",
        "Semantic channel mode (auto/on/off).",
    ),
    SettingSpec(
        "retrieval.semantic_rank_weight",
        "LEMONCROW_SEMANTIC_RANK_WEIGHT",
        "float",
        120,
        "retrieval",
        "Weight applied to the semantic channel's score during rank fusion.",
    ),
    SettingSpec(
        "retrieval.substring_anchor_df_cap",
        "LEMONCROW_SUBSTRING_ANCHOR_DF_CAP",
        "int",
        500,
        "retrieval",
        "Document-frequency cap for substring anchors used in lexical search.",
    ),
    SettingSpec(
        "retrieval.supplement_channel_deadline_s",
        "LEMONCROW_SUPPLEMENT_CHANNEL_DEADLINE_S",
        "float",
        0.08,
        "retrieval",
        "Deadline (seconds) for the supplemental (fast) search channel.",
    ),
    SettingSpec(
        "retrieval.retrieval_trace",
        "LEMONCROW_RETRIEVAL_TRACE",
        "bool",
        False,
        "retrieval",
        "Record a detailed trace of retrieval channel decisions for debugging.",
    ),
    SettingSpec(
        "retrieval.zoekt_ready_timeout_s",
        "LEMONCROW_ZOEKT_READY_TIMEOUT_S",
        "float",
        5.0,
        "retrieval",
        "Seconds to wait for the zoekt index server to become ready.",
    ),
    # -- code_context: indexing engine internals --
    SettingSpec(
        "code_context.ast_grep_bin",
        "LEMONCROW_AST_GREP_BIN",
        "str",
        "",
        "code_context",
        "Path to an ast-grep binary to use instead of the managed bootstrap install.",
    ),
    SettingSpec(
        "code_context.autosync_debounce_ms",
        "LEMONCROW_CODE_AUTOSYNC_DEBOUNCE_MS",
        "int",
        None,
        "code_context",
        "Debounce window (ms) before the code index re-syncs after a file change.",
    ),
    SettingSpec(
        "code_context.autosync_poll_ms",
        "LEMONCROW_CODE_AUTOSYNC_POLL_MS",
        "int",
        None,
        "code_context",
        "Poll interval (ms) the code index autosync uses to check for changes.",
    ),
    SettingSpec(
        "code_context.file_watcher",
        "LEMONCROW_CODE_FILE_WATCHER",
        "bool",
        None,
        "code_context",
        "Enable filesystem-watcher-driven incremental reindexing.",
    ),
    SettingSpec(
        "code_context.watcher_debounce_ms",
        "LEMONCROW_CODE_WATCHER_DEBOUNCE_MS",
        "int",
        None,
        "code_context",
        "Debounce window (ms) for the filesystem watcher's reindex trigger.",
    ),
    SettingSpec(
        "code_context.doc_indexing",
        "LEMONCROW_DOC_INDEXING",
        "bool",
        False,
        "code_context",
        "Index prose/doc files (README, markdown) into the retrieval store (off by default).",
    ),
    SettingSpec(
        "code_context.edit_reindex",
        "LEMONCROW_EDIT_REINDEX",
        "bool",
        True,
        "code_context",
        "Reindex a file automatically right after an edit tool call touches it.",
    ),
    SettingSpec(
        "code_context.edit_verify",
        "LEMONCROW_EDIT_VERIFY",
        "str",
        None,
        "code_context",
        "Post-edit verification mode (e.g. syntax-check level) applied after edit tool calls.",
    ),
    SettingSpec(
        "code_context.embed_batch_size",
        "LEMONCROW_EMBED_BATCH_SIZE",
        "int",
        None,
        "code_context",
        "Batch size used when embedding symbols/chunks during indexing.",
    ),
    SettingSpec(
        "code_context.embed_max_chars",
        "LEMONCROW_EMBED_MAX_CHARS",
        "int",
        4000,
        "code_context",
        "Max characters of source text embedded per chunk.",
    ),
    SettingSpec(
        "code_context.hef_fast_path",
        "LEMONCROW_HEF_FAST_PATH",
        "str",
        None,
        "code_context",
        "Toggle the hot-edit-file fast path used to skip full reindex on small edits.",
    ),
    SettingSpec(
        "code_context.history_enabled",
        "LEMONCROW_HISTORY_ENABLED",
        "bool",
        False,
        "code_context",
        "Enable git-history-aware code intelligence (commit lineage summaries).",
    ),
    SettingSpec(
        "code_context.history_bootstrap_commits",
        "LEMONCROW_HISTORY_BOOTSTRAP_COMMITS",
        "int",
        None,
        "code_context",
        "Number of commits to backfill when git-history indexing first bootstraps.",
    ),
    SettingSpec(
        "code_context.history_max_commits",
        "LEMONCROW_HISTORY_MAX_COMMITS",
        "int",
        None,
        "code_context",
        "Max commits considered per git-history walk.",
    ),
    SettingSpec(
        "code_context.index_lock_timeout_s",
        "LEMONCROW_INDEX_LOCK_TIMEOUT_S",
        "float",
        None,
        "code_context",
        "Seconds to wait for the code-index write lock before giving up.",
    ),
    SettingSpec(
        "code_context.index_max_workers",
        "LEMONCROW_INDEX_MAX_WORKERS",
        "int",
        None,
        "code_context",
        "Max parallel worker processes used to build the code index.",
    ),
    SettingSpec(
        "code_context.index_pool_context",
        "LEMONCROW_INDEX_POOL_CONTEXT",
        "str",
        "",
        "code_context",
        "Multiprocessing start-method context name for the index worker pool.",
    ),
    SettingSpec(
        "code_context.index_serial_max_files",
        "LEMONCROW_INDEX_SERIAL_MAX_FILES",
        "int",
        None,
        "code_context",
        "File-count threshold below which indexing runs serially instead of in a worker pool.",
    ),
    SettingSpec(
        "code_context.index_worker_max_mem_mb",
        "LEMONCROW_INDEX_WORKER_MAX_MEM_MB",
        "int",
        None,
        "code_context",
        "Memory ceiling (MB) per index worker process before it's recycled.",
    ),
    SettingSpec(
        "code_context.lineage_enabled",
        "LEMONCROW_LINEAGE_ENABLED",
        "bool",
        False,
        "code_context",
        "Fold git-blame/commit lineage into ranking and summaries.",
    ),
    SettingSpec(
        "code_context.lineage_commit_score_penalty",
        "LEMONCROW_LINEAGE_COMMIT_SCORE_PENALTY",
        "float",
        0.1,
        "code_context",
        "Score penalty applied per commit of staleness when lineage ranking is enabled.",
    ),
    SettingSpec(
        "code_context.lineage_model",
        "LEMONCROW_LINEAGE_MODEL",
        "str",
        "",
        "code_context",
        "Model id used to summarize git-history lineage.",
    ),
    SettingSpec(
        "code_context.line_skim",
        "LEMONCROW_LINE_SKIM",
        "bool",
        False,
        "code_context",
        "Enable line-skimming chunk projection (denser, lossier context chunks).",
    ),
    SettingSpec(
        "code_context.outline_threshold",
        "LEMONCROW_OUTLINE_THRESHOLD",
        "int",
        None,
        "code_context",
        "File-size threshold above which reads default to outline projection.",
    ),
    SettingSpec(
        "code_context.repomap_tag_cache",
        "LEMONCROW_REPOMAP_TAG_CACHE",
        "bool",
        None,
        "code_context",
        "Enable the on-disk tag cache for repo-map generation.",
    ),
    SettingSpec(
        "code_context.zoekt_gate",
        "LEMONCROW_ZOEKT_GATE",
        "bool",
        True,
        "code_context",
        "Allow the zoekt fast-path gate to short-circuit full-text search.",
    ),
    SettingSpec(
        "code_context.zoekt_gate_log",
        "LEMONCROW_ZOEKT_GATE_LOG",
        "bool",
        False,
        "code_context",
        "Log zoekt gate decisions for debugging.",
    ),
    # -- embeddings: embedder backend selection & model tuning --
    SettingSpec(
        "embeddings.embedder",
        "LEMONCROW_EMBEDDER",
        "str",
        "",
        "embeddings",
        "General-purpose embedder backend override (nomic/bge/ollama/openai).",
    ),
    SettingSpec(
        "embeddings.code_embedder",
        "LEMONCROW_CODE_EMBEDDER",
        "str",
        "nomic",
        "embeddings",
        "Embedder backend used for code indexing.",
    ),
    SettingSpec(
        "embeddings.code_embed_model",
        "LEMONCROW_CODE_EMBED_MODEL",
        "str",
        "",
        "embeddings",
        "Embedding model id used for code indexing.",
    ),
    SettingSpec(
        "embeddings.recall_embedder",
        "LEMONCROW_RECALL_EMBEDDER",
        "str",
        "",
        "embeddings",
        "Embedder backend used for session recall.",
    ),
    SettingSpec(
        "embeddings.recall_embed_model",
        "LEMONCROW_RECALL_EMBED_MODEL",
        "str",
        "",
        "embeddings",
        "Embedding model id used for session recall.",
    ),
    SettingSpec(
        "embeddings.embed_max_inflight",
        "LEMONCROW_EMBED_MAX_INFLIGHT",
        "int",
        3,
        "embeddings",
        "Max concurrent embedding requests in flight for archival recall.",
    ),
    SettingSpec(
        "embeddings.embed_timeout_s",
        "LEMONCROW_EMBED_TIMEOUT_S",
        "float",
        10,
        "embeddings",
        "Timeout (seconds) for a single embedding request in archival recall.",
    ),
    SettingSpec(
        "embeddings.recall_candidate_limit",
        "LEMONCROW_RECALL_CANDIDATE_LIMIT",
        "int",
        2000,
        "embeddings",
        "Max candidate chunks pulled before ranking in archival recall.",
    ),
    SettingSpec(
        "embeddings.bge_max_seq",
        "LEMONCROW_BGE_MAX_SEQ",
        "int",
        2048,
        "embeddings",
        "Max sequence length for the local BGE embedding model.",
    ),
    SettingSpec(
        "embeddings.nomic_dim",
        "LEMONCROW_NOMIC_DIM",
        "int",
        None,
        "embeddings",
        "Output vector dimensionality for the Nomic embedding model.",
    ),
    SettingSpec(
        "embeddings.nomic_max_seq",
        "LEMONCROW_NOMIC_MAX_SEQ",
        "int",
        8192,
        "embeddings",
        "Max sequence length for the Nomic embedding model.",
    ),
    SettingSpec(
        "embeddings.hf_doc_prefix",
        "LEMONCROW_HF_DOC_PREFIX",
        "str",
        None,
        "embeddings",
        "Prefix prepended to documents before embedding (Nomic-style instruction prefix).",
    ),
    SettingSpec(
        "embeddings.hf_query_prefix",
        "LEMONCROW_HF_QUERY_PREFIX",
        "str",
        None,
        "embeddings",
        "Prefix prepended to queries before embedding (Nomic-style instruction prefix).",
    ),
    SettingSpec(
        "embeddings.ollama_embed_timeout_seconds",
        "LEMONCROW_OLLAMA_EMBED_TIMEOUT_SECONDS",
        "float",
        None,
        "embeddings",
        "Timeout (seconds) for Ollama-backed embedding requests.",
    ),
    SettingSpec(
        "embeddings.rerank_batch",
        "LEMONCROW_RERANK_BATCH",
        "int",
        32,
        "embeddings",
        "Batch size for the cross-encoder reranker.",
    ),
    SettingSpec(
        "embeddings.rerank_max_seq",
        "LEMONCROW_RERANK_MAX_SEQ",
        "int",
        1024,
        "embeddings",
        "Max sequence length for the cross-encoder reranker.",
    ),
    SettingSpec(
        "embeddings.code_reranker_enabled",
        "LEMONCROW_CODE_RERANKER_ENABLED",
        "bool",
        True,
        "embeddings",
        "Enable the code-search reranker service.",
    ),
    SettingSpec(
        "embeddings.code_reranker_host",
        "LEMONCROW_CODE_RERANKER_HOST",
        "str",
        "",
        "embeddings",
        "Host URL of the code-search reranker service.",
    ),
    SettingSpec(
        "embeddings.code_reranker_model",
        "LEMONCROW_CODE_RERANKER_MODEL",
        "str",
        "",
        "embeddings",
        "Model id used by the code-search reranker service.",
    ),
    SettingSpec(
        "embeddings.code_reranker_min_candidates",
        "LEMONCROW_CODE_RERANKER_MIN_CANDIDATES",
        "int",
        8,
        "embeddings",
        "Minimum candidate count before the code-search reranker engages.",
    ),
    SettingSpec(
        "embeddings.code_reranker_top_n",
        "LEMONCROW_CODE_RERANKER_TOP_N",
        "int",
        15,
        "embeddings",
        "Number of top candidates the code-search reranker returns.",
    ),
    SettingSpec(
        "embeddings.code_reranker_max_latency_ms",
        "LEMONCROW_CODE_RERANKER_MAX_LATENCY_MS",
        "int",
        250,
        "embeddings",
        "Max latency (ms) budget for a code-search reranker call before it's skipped.",
    ),
    # -- tool_supervision: bash/edit/read/sql/search safety limits --
    SettingSpec(
        "tool_supervision.bash_allows_json",
        None,
        "str",
        "",
        "tool_supervision",
        "(install-time) Bash command allowlist baked into the host's settings.json at install.",
        settable=False,
    ),
    SettingSpec(
        "tool_supervision.shell_max_output_bytes",
        "LEMONCROW_SHELL_MAX_OUTPUT_BYTES",
        "int",
        4194304,
        "tool_supervision",
        "Hard ceiling on stdout/stderr bytes materialized from a single bash command.",
    ),
    SettingSpec(
        "tool_supervision.shell_max_spool_bytes",
        "LEMONCROW_SHELL_MAX_SPOOL_BYTES",
        "int",
        4194304,
        "tool_supervision",
        "On-disk ceiling for a managed command's temp spool file.",
    ),
    SettingSpec(
        "tool_supervision.search_max_candidates",
        "LEMONCROW_SEARCH_MAX_CANDIDATES",
        "int",
        20000,
        "tool_supervision",
        "Max candidate files scanned by the native grep/glob fallback.",
    ),
    SettingSpec(
        "tool_supervision.search_max_file_bytes",
        "LEMONCROW_SEARCH_MAX_FILE_BYTES",
        "int",
        5242880,
        "tool_supervision",
        "Max file size scanned by the native grep/glob fallback.",
    ),
    SettingSpec(
        "tool_supervision.sql_allow_external_db",
        "LEMONCROW_SQL_ALLOW_EXTERNAL_DB",
        "bool",
        False,
        "tool_supervision",
        "Allow the SQL tool to connect to databases outside the project workspace.",
    ),
    SettingSpec(
        "tool_supervision.sql_allow_writes",
        "LEMONCROW_SQL_ALLOW_WRITES",
        "bool",
        False,
        "tool_supervision",
        "Allow the SQL tool to run INSERT/UPDATE/DELETE/DDL statements.",
    ),
    SettingSpec(
        "tool_supervision.owned_max_tokens",
        "LEMONCROW_OWNED_MAX_TOKENS",
        "int",
        4096,
        "tool_supervision",
        "Max output tokens for a tool call run through an owned execution lane.",
    ),
    SettingSpec(
        "tool_supervision.owned_max_output_chars",
        "LEMONCROW_OWNED_MAX_OUTPUT_CHARS",
        "int",
        None,
        "tool_supervision",
        "Max output characters for a tool call run through an owned execution lane.",
    ),
    SettingSpec(
        "tool_supervision.owned_timeout_s",
        "LEMONCROW_OWNED_TIMEOUT_S",
        "float",
        180.0,
        "tool_supervision",
        "Wall-clock timeout (seconds) for a tool call run through an owned execution lane.",
    ),
    SettingSpec(
        "tool_supervision.read_after_edit_guard",
        "LEMONCROW_READ_AFTER_EDIT_GUARD",
        "bool",
        True,
        "tool_supervision",
        "Require a fresh read before editing a file the agent hasn't seen this session.",
    ),
    SettingSpec(
        "tool_supervision.read_baseline_dedup",
        "LEMONCROW_READ_BASELINE_DEDUP",
        "bool",
        True,
        "tool_supervision",
        "Skip re-reading file content already returned verbatim earlier this session.",
    ),
    SettingSpec(
        "tool_supervision.read_max_bytes",
        "LEMONCROW_READ_MAX_BYTES",
        "int",
        8388608,
        "tool_supervision",
        "Hard ceiling on bytes read from a single file.",
    ),
    SettingSpec(
        "tool_supervision.read_inline_budget_bytes",
        "LEMONCROW_READ_INLINE_BUDGET_BYTES",
        "int",
        40960,
        "tool_supervision",
        "Bytes of tool output returned inline before it's written to a spill file.",
    ),
    SettingSpec(
        "tool_supervision.contract_review",
        "LEMONCROW_CONTRACT_REVIEW",
        "bool",
        True,
        "tool_supervision",
        "Run the contract-review check (caller/signature drift) after edits.",
    ),
    SettingSpec(
        "tool_supervision.loop_review",
        "LEMONCROW_LOOP_REVIEW",
        "bool",
        True,
        "tool_supervision",
        "Run the live-loop reviewer pass during long tool-call sequences.",
    ),
    SettingSpec(
        "tool_supervision.external_compactors",
        "LEMONCROW_BASH_EXTERNAL_COMPACTORS",
        "bool",
        True,
        "tool_supervision",
        "Soft-detect an installed external command-compactor binary (e.g. rtk) and pass a "
        "narrow allowlist of read-only/idempotent shell commands (git/gh inspection, test "
        "runners, linters) through it for token-compact output. On by default -- used "
        "automatically when found on PATH; never a hard dependency -- falls back to the normal "
        "shell path when the binary is absent. Set false to opt out even when installed.",
    ),
    SettingSpec(
        "tool_supervision.test_contract_guard",
        "LEMONCROW_TEST_CONTRACT_GUARD",
        "bool",
        True,
        "tool_supervision",
        "Guard against edits that silently change test contracts.",
    ),
    SettingSpec(
        "tool_supervision.defer_edit_hooks",
        "LEMONCROW_DEFER_EDIT_HOOKS",
        "bool",
        False,
        "tool_supervision",
        "Defer post-edit hooks (lint/format/verify) to run in the background instead of inline.",
    ),
    SettingSpec(
        "tool_supervision.perplexity_compression",
        "LEMONCROW_PERPLEXITY_COMPRESSION",
        "bool",
        False,
        "tool_supervision",
        "Enable perplexity-based context pruning/compression.",
    ),
    SettingSpec(
        "tool_supervision.context_window_tokens",
        "LEMONCROW_CONTEXT_WINDOW_TOKENS",
        "int",
        None,
        "tool_supervision",
        "Override the model context-window size LemonCrow budgets against.",
    ),
    SettingSpec(
        "tool_supervision.ctx_nudge_tokens",
        "LEMONCROW_CTX_NUDGE_TOKENS",
        "int",
        None,
        "tool_supervision",
        "Token count at which LemonCrow nudges the agent about context occupancy.",
    ),
    SettingSpec(
        "tool_supervision.tool_profile_path",
        "LEMONCROW_TOOL_PROFILE_PATH",
        "str",
        "",
        "tool_supervision",
        "Path to a custom tool-profile config controlling which tools are exposed.",
    ),
    # -- mcp: MCP server transport & result-shaping --
    SettingSpec("mcp.debug", "LEMONCROW_MCP_DEBUG", "bool", False, "mcp", "Verbose MCP server debug logging."),
    SettingSpec(
        "mcp.max_workers",
        "LEMONCROW_MCP_MAX_WORKERS",
        "int",
        16,
        "mcp",
        "Max worker threads for concurrent MCP tool execution.",
    ),
    SettingSpec(
        "mcp.heavy_workers",
        "LEMONCROW_MCP_HEAVY_WORKERS",
        "int",
        6,
        "mcp",
        "Max worker threads reserved for heavy (indexing/embedding) MCP tool calls.",
    ),
    SettingSpec(
        "mcp.io_workers",
        "LEMONCROW_MCP_IO_WORKERS",
        "int",
        None,
        "mcp",
        "Max worker threads reserved for I/O-bound MCP tool calls.",
    ),
    SettingSpec(
        "mcp.max_result_bytes",
        "LEMONCROW_MCP_MAX_RESULT_BYTES",
        "int",
        6291456,
        "mcp",
        "Hard ceiling on a single MCP tool result payload.",
    ),
    SettingSpec(
        "mcp.compact_result_chars",
        "LEMONCROW_MCP_COMPACT_RESULT_CHARS",
        "int",
        262144,
        "mcp",
        "Character threshold above which MCP results are compacted before returning.",
    ),
    SettingSpec(
        "mcp.spill_result_chars",
        "LEMONCROW_MCP_SPILL_RESULT_CHARS",
        "int",
        None,
        "mcp",
        "Character threshold above which an MCP result is written to a spill file instead of inlined.",
    ),
    SettingSpec(
        "mcp.spill_dir", "LEMONCROW_MCP_SPILL_DIR", "str", "", "mcp", "Directory large tool outputs are spilled to."
    ),
    SettingSpec(
        "mcp.spill_max_files",
        "LEMONCROW_MCP_SPILL_MAX_FILES",
        "int",
        512,
        "mcp",
        "Max number of spill files retained before the oldest are pruned.",
    ),
    SettingSpec(
        "mcp.spill_ttl_seconds",
        "LEMONCROW_MCP_SPILL_TTL_SECONDS",
        "int",
        86400,
        "mcp",
        "Time-to-live (seconds) for spilled tool-output files.",
    ),
    SettingSpec(
        "mcp.http",
        "LEMONCROW_MCP_HTTP",
        "bool",
        False,
        "mcp",
        "Expose the MCP server over HTTP (in addition to stdio).",
    ),
    SettingSpec(
        "mcp.http_max_body_bytes",
        "LEMONCROW_MCP_HTTP_MAX_BODY_BYTES",
        "int",
        4194304,
        "mcp",
        "Max request body size accepted by the MCP HTTP transport.",
    ),
    SettingSpec(
        "mcp.http_allow_project_override",
        "LEMONCROW_HTTP_ALLOW_PROJECT_OVERRIDE",
        "bool",
        False,
        "mcp",
        "Allow a project-local config to override MCP HTTP settings.",
    ),
    SettingSpec(
        "mcp.defer_bash",
        "LEMONCROW_MCP_DEFER_BASH",
        "bool",
        True,
        "mcp",
        "Run long bash commands as deferred/background MCP tool calls.",
    ),
    SettingSpec(
        "mcp.defer_web_fetch",
        "LEMONCROW_MCP_DEFER_WEB_FETCH",
        "bool",
        True,
        "mcp",
        "Run web_fetch as a deferred/background MCP tool call.",
    ),
    SettingSpec(
        "mcp.tool_output_spill",
        "LEMONCROW_TOOL_OUTPUT_SPILL",
        "bool",
        True,
        "mcp",
        "Enable spilling large tool output to disk instead of inlining it.",
    ),
    SettingSpec(
        "mcp.allow_untrusted",
        "LEMONCROW_MCP_ALLOW_UNTRUSTED",
        "bool",
        False,
        "mcp",
        "Opt in to loading MCP servers from untrusted/unpinned sources.",
    ),
    SettingSpec(
        "mcp.hide_tools",
        "LEMONCROW_HIDE_TOOLS",
        "str",
        "",
        "mcp",
        "Comma-separated extra tool names to hide from the LLM-visible tool surface.",
    ),
    SettingSpec(
        "mcp.show_all",
        "LEMONCROW_SHOW_ALL",
        "bool",
        False,
        "mcp",
        "Show normally-hidden internal CLI commands in --help output.",
    ),
    SettingSpec(
        "mcp.auto_compact_output",
        "LEMONCROW_AUTO_COMPACT_OUTPUT",
        "bool",
        False,
        "mcp",
        "Emit compaction-savings output after an auto-compact runs.",
    ),
    SettingSpec(
        "mcp.trace_max_files",
        "LEMONCROW_TRACE_MAX_FILES",
        "int",
        50,
        "mcp",
        "Max number of trace files retained before the oldest are pruned.",
    ),
    SettingSpec(
        "mcp.trace_max_file_bytes",
        "LEMONCROW_TRACE_MAX_FILE_BYTES",
        "int",
        1048576,
        "mcp",
        "Max size of a single trace file before it rolls over.",
    ),
    # -- statusline: live segment values fed to the statusline renderer --
    SettingSpec(
        "statusline.cost_usd",
        "LEMONCROW_STATUSLINE_COST_USD",
        "float",
        None,
        "statusline",
        "Live session cost (USD) injected into the statusline segment.",
        settable=False,
    ),
    SettingSpec(
        "statusline.live_in_tok",
        "LEMONCROW_STATUSLINE_LIVE_IN_TOK",
        "int",
        None,
        "statusline",
        "Live input-token count injected into the statusline segment.",
        settable=False,
    ),
    SettingSpec(
        "statusline.live_out_tok",
        "LEMONCROW_STATUSLINE_LIVE_OUT_TOK",
        "int",
        None,
        "statusline",
        "Live output-token count injected into the statusline segment.",
        settable=False,
    ),
    SettingSpec(
        "statusline.live_cache_tok",
        "LEMONCROW_STATUSLINE_LIVE_CACHE_TOK",
        "int",
        None,
        "statusline",
        "Live cache-token count injected into the statusline segment.",
        settable=False,
    ),
    SettingSpec(
        "statusline.no_color",
        "LEMONCROW_STATUSLINE_NO_COLOR",
        "bool",
        False,
        "statusline",
        "Disable ANSI color in the statusline output.",
    ),
    SettingSpec(
        "statusline.compact",
        "LEMONCROW_STATUSLINE_COMPACT",
        "bool",
        False,
        "statusline",
        "Use the compact statusline layout (model · ctx % · savings) at install time.",
        settable=False,
    ),
    SettingSpec(
        "statusline.session_id",
        "LEMONCROW_STATUS_SESSION_ID",
        "str",
        "",
        "statusline",
        "Session id the statusline renderer reports savings/state for.",
        settable=False,
    ),
    SettingSpec(
        "statusline.no_color_generic",
        "LEMONCROW_NO_COLOR",
        "bool",
        False,
        "statusline",
        "Disable ANSI color across LemonCrow CLI/statusline output.",
    ),
    # -- telemetry: OTel/PostHog + local rollup --
    SettingSpec(
        "telemetry.posthog_key",
        "LEMONCROW_POSTHOG_KEY",
        "str",
        "",
        "telemetry",
        "PostHog project API key for anonymous product telemetry.",
    ),
    SettingSpec(
        "telemetry.posthog_host",
        "LEMONCROW_POSTHOG_HOST",
        "str",
        "https://us.i.posthog.com",
        "telemetry",
        "PostHog ingestion host.",
    ),
    SettingSpec(
        "telemetry.otel_endpoint",
        "LEMONCROW_OTEL_ENDPOINT",
        "str",
        "http://localhost:4318",
        "telemetry",
        "OpenTelemetry collector endpoint traces/metrics are exported to.",
    ),
    SettingSpec(
        "telemetry.public_endpoint",
        "LEMONCROW_PUBLIC_TELEMETRY_ENDPOINT",
        "str",
        "https://lemoncrow.com/api/telemetry/rollup",
        "telemetry",
        "Endpoint the opt-in public savings rollup is posted to.",
    ),
    SettingSpec(
        "telemetry.public_timeout_ms",
        "LEMONCROW_PUBLIC_TELEMETRY_TIMEOUT_MS",
        "int",
        None,
        "telemetry",
        "Timeout (ms) for the public telemetry rollup POST.",
    ),
    SettingSpec(
        "telemetry.allow_in_tests",
        "LEMONCROW_TELEMETRY_ALLOW_IN_TESTS",
        "bool",
        False,
        "telemetry",
        "Allow telemetry to fire during pytest runs (normally suppressed).",
    ),
    SettingSpec(
        "telemetry.config_path",
        "LEMONCROW_TELEMETRY_CONFIG",
        "str",
        "",
        "telemetry",
        "Override path to telemetry.toml (opt-out state).",
    ),
    SettingSpec(
        "telemetry.db_path",
        "LEMONCROW_TELEMETRY_DB",
        "str",
        "",
        "telemetry",
        "Override path to the local telemetry SQLite database.",
    ),
    SettingSpec(
        "telemetry.id_path",
        "LEMONCROW_TELEMETRY_ID_PATH",
        "str",
        "",
        "telemetry",
        "Override path to the anonymous installation id file.",
    ),
    SettingSpec(
        "telemetry.ack_path",
        "LEMONCROW_TELEMETRY_ACK",
        "str",
        "",
        "telemetry",
        "Override path to the telemetry-notice acknowledgement flag file.",
    ),
    SettingSpec(
        "telemetry.hide_missing_login",
        "LEMONCROW_HIDE_MISSING_LOGIN",
        "bool",
        False,
        "telemetry",
        'Suppress the "not logged in" nudge in savings/status output.',
    ),
    SettingSpec(
        "telemetry.langfuse_enabled",
        "LEMONCROW_LANGFUSE_ENABLED",
        "bool",
        False,
        "telemetry",
        "Export traces to Langfuse.",
    ),
    # -- memory: memory backend + bridges --
    SettingSpec(
        "memory.backend",
        "LEMONCROW_MEMORY_BACKEND",
        "str",
        "sqlite",
        "memory",
        "Memory backend: sqlite, letta, or openmemory.",
    ),
    SettingSpec(
        "memory.letta_url",
        "LEMONCROW_LETTA_URL",
        "str",
        "http://localhost:8283",
        "memory",
        "Base URL of the Letta memory server.",
    ),
    SettingSpec(
        "memory.letta_api_key", "LEMONCROW_LETTA_API_KEY", "str", "", "memory", "API key for the Letta memory server."
    ),
    SettingSpec(
        "memory.openmemory_url",
        "LEMONCROW_OPENMEMORY_URL",
        "str",
        "http://127.0.0.1:8765",
        "memory",
        "Base URL of the OpenMemory server.",
    ),
    SettingSpec(
        "memory.openmemory_client_name",
        "LEMONCROW_OPENMEMORY_CLIENT_NAME",
        "str",
        "lemoncrow",
        "memory",
        "Client name LemonCrow registers with OpenMemory.",
    ),
    SettingSpec(
        "memory.openmemory_http_path",
        "LEMONCROW_OPENMEMORY_HTTP_PATH",
        "str",
        "",
        "memory",
        "HTTP path override for the OpenMemory MCP endpoint.",
    ),
    SettingSpec(
        "memory.openmemory_mcp_protocol_version",
        "LEMONCROW_OPENMEMORY_MCP_PROTOCOL_VERSION",
        "str",
        "",
        "memory",
        "MCP protocol version string sent to OpenMemory.",
    ),
    SettingSpec(
        "memory.openmemory_openai_api_key",
        "LEMONCROW_OPENMEMORY_OPENAI_API_KEY",
        "str",
        "",
        "memory",
        "OpenAI API key used by the OpenMemory server (falls back to OPENAI_API_KEY).",
    ),
    SettingSpec(
        "memory.openmemory_repo_url",
        "LEMONCROW_OPENMEMORY_REPO_URL",
        "str",
        "https://github.com/mem0ai/mem0.git",
        "memory",
        "Repo URL LemonCrow clones to bootstrap OpenMemory.",
    ),
    SettingSpec(
        "memory.openmemory_ref",
        "LEMONCROW_OPENMEMORY_REF",
        "str",
        "main",
        "memory",
        "Git ref checked out when bootstrapping OpenMemory.",
    ),
    SettingSpec(
        "memory.openmemory_timeout_seconds",
        "LEMONCROW_OPENMEMORY_TIMEOUT_SECONDS",
        "int",
        15,
        "memory",
        "Request timeout (seconds) for OpenMemory calls.",
    ),
    SettingSpec(
        "memory.openmemory_user_id",
        "LEMONCROW_OPENMEMORY_USER_ID",
        "str",
        "",
        "memory",
        "User id namespace used for OpenMemory records (defaults to $USER).",
    ),
    # -- swarm: isolated multi-agent run coordination --
    SettingSpec(
        "swarm.effort",
        "LEMONCROW_SWARM_EFFORT",
        "str",
        "",
        "swarm",
        "Default reasoning-effort level for swarm child runs.",
    ),
    SettingSpec("swarm.model", "LEMONCROW_SWARM_MODEL", "str", "", "swarm", "Default model id for swarm child runs."),
    SettingSpec(
        "swarm.provider", "LEMONCROW_SWARM_PROVIDER", "str", "", "swarm", "Default provider for swarm child runs."
    ),
    SettingSpec(
        "swarm.step_budget",
        "LEMONCROW_SWARM_STEP_BUDGET",
        "int",
        10,
        "swarm",
        "Default max tool-call steps per swarm child before it's stopped.",
    ),
    SettingSpec(
        "swarm.time_budget_seconds",
        "LEMONCROW_SWARM_TIME_BUDGET_SECONDS",
        "int",
        240,
        "swarm",
        "Default wall-clock budget (seconds) per swarm child.",
    ),
    SettingSpec(
        "swarm.child_id",
        "LEMONCROW_SWARM_CHILD_ID",
        "str",
        "",
        "swarm",
        "Child id assigned by the parent swarm run (generated, informational).",
        settable=False,
    ),
    SettingSpec(
        "swarm.run_id",
        "LEMONCROW_SWARM_RUN_ID",
        "str",
        "",
        "swarm",
        "Run id assigned by the parent swarm run (generated, informational).",
        settable=False,
    ),
    SettingSpec(
        "swarm.base_ref",
        "LEMONCROW_SWARM_BASE_REF",
        "str",
        "",
        "swarm",
        "Git ref the swarm run's integration branch is based on (generated, informational).",
        settable=False,
    ),
    SettingSpec(
        "swarm.result_path",
        "LEMONCROW_SWARM_RESULT_PATH",
        "str",
        "",
        "swarm",
        "Path a swarm child writes its result to (generated, informational).",
        settable=False,
    ),
    SettingSpec(
        "swarm.metadata_path",
        "LEMONCROW_SWARM_METADATA_PATH",
        "str",
        "",
        "swarm",
        "Path to the swarm run's metadata file (generated, informational).",
        settable=False,
    ),
    SettingSpec(
        "swarm.spec_path",
        "LEMONCROW_SWARM_SPEC_PATH",
        "str",
        "",
        "swarm",
        "Path to the swarm run's spec file (generated, informational).",
        settable=False,
    ),
    # -- zoekt: fast full-text index binary/server --
    SettingSpec(
        "zoekt.bin",
        "LEMONCROW_ZOEKT_BIN",
        "str",
        "",
        "zoekt",
        "Path to a zoekt binary to use instead of the managed bootstrap install.",
    ),
    SettingSpec(
        "zoekt.bin_sha256",
        "LEMONCROW_ZOEKT_BIN_SHA256",
        "str",
        "",
        "zoekt",
        "Expected SHA-256 of the zoekt binary (integrity pin for a custom binary).",
    ),
    SettingSpec(
        "zoekt.mode", "LEMONCROW_ZOEKT_MODE", "str", "", "zoekt", "zoekt integration mode override (e.g. off)."
    ),
    SettingSpec(
        "zoekt.loc_threshold",
        "LEMONCROW_ZOEKT_LOC_THRESHOLD",
        "int",
        None,
        "zoekt",
        "Repo line-count threshold above which zoekt indexing is used.",
    ),
    SettingSpec(
        "zoekt.request_timeout_ms",
        "LEMONCROW_ZOEKT_REQUEST_TIMEOUT_MS",
        "int",
        None,
        "zoekt",
        "Timeout (ms) for a single zoekt query.",
    ),
    # -- bench: benchmark harness --
    SettingSpec(
        "bench.mode",
        "LEMONCROW_BENCH_MODE",
        "str",
        "",
        "bench",
        "Benchmark harness mode (on/off/shadow) gating bench-only tool behavior.",
    ),
    SettingSpec("bench.model", "LEMONCROW_BENCH_MODEL", "str", "", "bench", "Model id used for benchmark runs."),
    SettingSpec(
        "bench.effort",
        "LEMONCROW_BENCH_EFFORT",
        "str",
        "",
        "bench",
        "Reasoning-effort override applied to benchmark runs.",
    ),
    SettingSpec(
        "bench.disallowed_tools",
        "LEMONCROW_BENCH_DISALLOWED_TOOLS",
        "str",
        "",
        "bench",
        "Comma-separated tool names to disallow while benchmarking.",
    ),
    SettingSpec(
        "bench.token_slots",
        "LEMONCROW_BENCH_TOKEN_SLOTS",
        "int",
        None,
        "bench",
        "Parallel token slots per OAuth token during benchmarking.",
    ),
    # -- routing: model tier/host routing --
    SettingSpec(
        "routing.tier_routing",
        "LEMONCROW_TIER_ROUTING",
        "str",
        "",
        "routing",
        "Override the model-tier routing decision (which model class handles a task).",
    ),
    SettingSpec(
        "routing.learned_routing",
        "LEMONCROW_LEARNED_ROUTING",
        "bool",
        False,
        "routing",
        "Use the learned success-predictor for model routing instead of static rules.",
    ),
    SettingSpec(
        "routing.learned_routing_threshold",
        "LEMONCROW_LEARNED_ROUTING_THRESHOLD",
        "float",
        0.9,
        "routing",
        "Confidence threshold for the learned routing predictor to act.",
    ),
    SettingSpec(
        "routing.learned_routing_min_samples",
        "LEMONCROW_LEARNED_ROUTING_MIN_SAMPLES",
        "int",
        20,
        "routing",
        "Minimum historical samples before learned routing is trusted.",
    ),
    SettingSpec(
        "routing.enforce_route_model",
        "LEMONCROW_ENFORCE_ROUTE_MODEL",
        "str",
        "",
        "routing",
        "Force all routed calls onto a single model id, bypassing tier routing.",
    ),
    SettingSpec(
        "routing.host_router_enable",
        "LEMONCROW_HOST_ROUTER_ENABLE",
        "bool",
        False,
        "routing",
        "Enable the host-router enforcement bridge (proxy tool calls through an upstream router).",
    ),
    SettingSpec(
        "routing.host_router_mode", "LEMONCROW_HOST_ROUTER_MODE", "str", "", "routing", "Host-router bridge mode."
    ),
    SettingSpec(
        "routing.host_router_upstream_base_url",
        "LEMONCROW_HOST_ROUTER_UPSTREAM_BASE_URL",
        "str",
        "http://127.0.0.1:4000",
        "routing",
        "Upstream base URL the host-router bridge forwards to.",
    ),
    SettingSpec(
        "routing.local_slm_url",
        "LEMONCROW_LOCAL_SLM_URL",
        "str",
        "",
        "routing",
        "Base URL of a local small-language-model server used for cheap routing decisions.",
    ),
    # -- llm: internal LLM backend used by LemonCrow's own reasoning calls --
    SettingSpec(
        "llm.backend",
        "LEMONCROW_LLM_BACKEND",
        "str",
        "none",
        "llm",
        "Internal LLM backend LemonCrow uses for its own reasoning calls (none/openai/ollama/litellm).",
    ),
    SettingSpec("llm.max_retries", "LEMONCROW_LLM_MAX_RETRIES", "int", 6, "llm", "Max retries for internal LLM calls."),
    SettingSpec(
        "llm.retry_base_seconds",
        "LEMONCROW_LLM_RETRY_BASE_SECONDS",
        "float",
        8,
        "llm",
        "Base backoff (seconds) between internal LLM call retries.",
    ),
    SettingSpec(
        "llm.internal_cache", "LEMONCROW_INTERNAL_LLM_CACHE", "bool", True, "llm", "Cache internal LLM call results."
    ),
    SettingSpec(
        "llm.internal_cache_max_entries",
        "LEMONCROW_INTERNAL_LLM_CACHE_MAX_ENTRIES",
        "int",
        None,
        "llm",
        "Max entries kept in the internal LLM call cache.",
    ),
    SettingSpec(
        "llm.litellm_model",
        "LEMONCROW_LITELLM_MODEL",
        "str",
        "gpt-4o-mini",
        "llm",
        "Model id used for LiteLLM-routed internal calls.",
    ),
    SettingSpec(
        "llm.openai_api_key",
        "LEMONCROW_OPENAI_API_KEY",
        "str",
        "",
        "llm",
        "OpenAI API key for internal LLM calls (falls back to OPENAI_API_KEY).",
    ),
    SettingSpec(
        "llm.openai_base_url",
        "LEMONCROW_OPENAI_BASE_URL",
        "str",
        "",
        "llm",
        "Base URL override for OpenAI-compatible internal LLM calls.",
    ),
    SettingSpec(
        "llm.openai_model",
        "LEMONCROW_OPENAI_MODEL",
        "str",
        "gpt-4o-mini",
        "llm",
        "Model id used for OpenAI-compatible internal LLM calls.",
    ),
    SettingSpec(
        "llm.ollama_model",
        "LEMONCROW_OLLAMA_MODEL",
        "str",
        "",
        "llm",
        "Model id used for Ollama-backed internal LLM calls.",
    ),
    # -- licensing --
    SettingSpec(
        "licensing.auth_token",
        "LEMONCROW_AUTH_TOKEN",
        "str",
        "",
        "licensing",
        "OAuth session token created by `lc account login`; used for plan checks.",
    ),
    SettingSpec(
        "licensing.pro_url",
        "LEMONCROW_PRO_URL",
        "str",
        "",
        "licensing",
        "URL surfaced for upgrading to the licensed/Pro tier.",
    ),
    # -- lessons --
    SettingSpec(
        "lessons.cluster_threshold",
        "LEMONCROW_LESSON_CLUSTER_THRESHOLD",
        "float",
        0.85,
        "lessons",
        "Similarity threshold for clustering related lessons during promotion.",
    ),
    SettingSpec(
        "lessons.pr_bot_enabled",
        "LEMONCROW_LESSON_PR_BOT_ENABLED",
        "bool",
        False,
        "lessons",
        "Enable the lesson-promotion bot to open PRs for promoted lessons.",
    ),
    # -- cli: general CLI/runtime toggles --
    SettingSpec(
        "cli.auto_compact",
        "LEMONCROW_AUTO_COMPACT",
        "bool",
        False,
        "cli",
        "Enable automatic context compaction in the runtime engine loop.",
    ),
    SettingSpec(
        "cli.auto_update",
        "LEMONCROW_AUTO_UPDATE",
        "bool",
        True,
        "cli",
        "Automatically install available LemonCrow updates instead of only notifying.",
    ),
    SettingSpec(
        "cli.auto_update_release",
        "LEMONCROW_AUTO_UPDATE_RELEASE",
        "bool",
        True,
        "cli",
        "Allow the background service-lifecycle updater to pull new releases automatically.",
    ),
    SettingSpec(
        "cli.cache_disabled",
        "LEMONCROW_CACHE_DISABLED",
        "bool",
        False,
        "cli",
        "Disable LemonCrow's internal result caches (debugging aid).",
    ),
    SettingSpec(
        "cli.offline",
        "LEMONCROW_OFFLINE",
        "bool",
        False,
        "cli",
        "Force offline mode: skip network calls that aren't strictly required.",
    ),
    SettingSpec(
        "cli.output_redaction",
        "LEMONCROW_OUTPUT_REDACTION",
        "str",
        None,
        "cli",
        "Redaction policy applied to tool output before it's returned (e.g. secrets masking level).",
    ),
    SettingSpec(
        "cli.in_review",
        "LEMONCROW_IN_REVIEW",
        "bool",
        False,
        "cli",
        "Marks the process as running inside a live-review child (internal reentrancy guard).",
        settable=False,
    ),
    SettingSpec(
        "cli.reviewer_child_cmd",
        "LEMONCROW_REVIEWER_CHILD_CMD",
        "str",
        "",
        "cli",
        "Override the command used to spawn the live-review child process.",
    ),
    SettingSpec(
        "cli.machine_id",
        "LEMONCROW_MACHINE_ID",
        "str",
        "",
        "cli",
        "Stable machine fingerprint seed used for anonymous ids.",
    ),
    SettingSpec(
        "cli.telegraphic",
        "LEMONCROW_TELEGRAPHIC",
        "str",
        "ultra",
        "cli",
        "Reply-register level baked into installed agent personas: ultra | lite | off. Setting it regenerates installed host agents (see lemoncrow.core.reply_register).",
    ),
    # -- core: bootstrap/location knobs (read-only through this surface) --
    SettingSpec(
        "core.root",
        "LEMONCROW_ROOT",
        "str",
        None,
        "core",
        "Runtime store root for traces, SQLite state, and this settings file. Set via env or --root; can't be set through this file (it decides where the file lives).",
        settable=False,
    ),
    SettingSpec(
        "core.store_root",
        "LEMONCROW_STORE_ROOT",
        "str",
        None,
        "core",
        "Legacy alias for LEMONCROW_ROOT.",
        settable=False,
    ),
    SettingSpec(
        "core.workspace_root",
        "LEMONCROW_WORKSPACE_ROOT",
        "str",
        None,
        "core",
        "Project workspace root the current session's tools operate on (set by the host per-session).",
        settable=False,
    ),
    SettingSpec(
        "core.install_dir",
        "LEMONCROW_INSTALL_DIR",
        "str",
        "",
        "core",
        "Directory LemonCrow was installed into (used by self-update).",
        settable=False,
    ),
    SettingSpec(
        "core.agent_host",
        "LEMONCROW_AGENT",
        "str",
        "",
        "core",
        "Name of the hosting agent/CLI (e.g. opencode) so output can be adapted for that host.",
    ),
    SettingSpec(
        "core.model",
        "LEMONCROW_MODEL",
        "str",
        "",
        "core",
        "Override the model id LemonCrow reports/uses when the host doesn't supply one.",
    ),
    SettingSpec(
        "core.non_interactive",
        "LEMONCROW_NON_INTERACTIVE",
        "bool",
        False,
        "core",
        "Force non-interactive mode across CLI prompts.",
    ),
    SettingSpec(
        "core.verify_before_done",
        "LEMONCROW_VERIFY_BEFORE_DONE",
        "bool",
        True,
        "core",
        "Require a verify pass before a task can be marked done.",
    ),
    SettingSpec(
        "core.verify_completeness",
        "LEMONCROW_VERIFY_COMPLETENESS",
        "bool",
        True,
        "core",
        "Include the completeness check in the verify-before-done gate.",
    ),
    # -- internal: process-managed, mostly informational --
    SettingSpec(
        "internal.mitm_active",
        "LEMONCROW_MITM_ACTIVE",
        "bool",
        False,
        "internal",
        "Set by the LemonCrow MITM proxy on itself while active (internal signal).",
        settable=False,
    ),
]

CATEGORIES: list[str] = sorted({spec.category for spec in SETTINGS})
