#!/usr/bin/env bash
# Atelier statusLine script for Claude Code.
# Prints one compact row that fits inside Claude's native agent frame:
#   atelier | Sonnet ctx 50k 35% · $0.012(I:30k C:10k O:5k) ↓ $0.045(R:12k C:2k)
#
# The dynamic segment (total saved/carry/weekly/monthly/vs-CC) is
# generated by the Python backend (atelier savings --segment) and rotates
# every few seconds so the line stays compact. All formatting lives there.

set -u
input=$(cat)
PLUGIN_LABEL="❯ atelier"

if command -v jq >/dev/null 2>&1; then
  # Use a non-whitespace delimiter so Bash preserves empty fields.
  ATELIER_STATUS_DELIM=$'\037'
  IFS="${ATELIER_STATUS_DELIM}" read -r MODEL PCT COST IN_TOK OUT_TOK CACHE_R CACHE_W SESSION_ID MODEL_ID TRANSCRIPT_PATH <<<"$(printf '%s' "$input" | jq -r '
    [
      (.model.display_name // .model.id // "claude"),
      (.context_window.used_percentage // 0),
      (.cost.total_cost_usd // 0),
      (.context_window.current_usage.input_tokens // 0),
      (.context_window.current_usage.output_tokens // 0),
      (.context_window.current_usage.cache_read_input_tokens // 0),
      (.context_window.current_usage.cache_creation_input_tokens // 0),
      (.session_id // ""),
      (.model.id // .model.display_name // ""),
      (.transcript_path // "")
    ] | map(tostring) | join("")
  ' 2>/dev/null)"
else
  read_field() {
    python3 -c "
import json, sys
try:
    d = json.loads(sys.argv[1] or '{}')
    keys = sys.argv[2].split('.')
    v = d
    for k in keys:
        if isinstance(v, dict):
            v = v.get(k)
        else:
            v = None
            break
    if v is None:
        v = sys.argv[3]
    print(v)
except Exception:
    print(sys.argv[3])
" "$input" "$1" "$2"
  }
  MODEL=$(read_field "model.display_name" "$(read_field "model.id" "claude")")
  MODEL_ID=$(read_field "model.id" "$MODEL")
  PCT=$(read_field "context_window.used_percentage" "0")
  COST=$(read_field "cost.total_cost_usd" "0")
  IN_TOK=$(read_field "context_window.current_usage.input_tokens" "0")
  OUT_TOK=$(read_field "context_window.current_usage.output_tokens" "0")
  CACHE_R=$(read_field "context_window.current_usage.cache_read_input_tokens" "0")
  CACHE_W=$(read_field "context_window.current_usage.cache_creation_input_tokens" "0")
  SESSION_ID=$(read_field "session_id" "")
  TRANSCRIPT_PATH=$(read_field "transcript_path" "")
fi

PCT_INT=${PCT%%.*}
[ -z "$PCT_INT" ] && PCT_INT=0

ATELIER_STATUS_ROOT="${ATELIER_ROOT:-${ATELIER_STORE_ROOT:-${HOME}/.atelier}}"
export ATELIER_STATUS_ROOT
export ATELIER_ROOT="${ATELIER_STATUS_ROOT}"

# --- Pro icon: rotate the leading glyph when the cached plan is pro/enterprise ---
# Reads the cached `/api/auth/me` response (written by `atelier login`;
# ~/.atelier/auth_user.json, see licensing/store.py). Any staleness within its
# normal cache TTL is fine here -- purely cosmetic, never a feature gate.
_ATELIER_AUTH_USER="${ATELIER_STATUS_ROOT}/auth_user.json"
if [ -f "${_ATELIER_AUTH_USER}" ]; then
  if command -v jq >/dev/null 2>&1; then
    _ATELIER_PLAN=$(jq -r '.plan // ""' "${_ATELIER_AUTH_USER}" 2>/dev/null)
  else
    _ATELIER_PLAN=$(python3 -c "
import json, sys
try:
    print(json.load(open(sys.argv[1])).get('plan', ''))
except Exception:
    print('')
" "${_ATELIER_AUTH_USER}" 2>/dev/null)
  fi
  case "${_ATELIER_PLAN:-}" in
    pro|enterprise)
      # Wall-clock rotation (5s per icon), same cadence as the dynamic segment
      # below -- deterministic within a render, no flicker.
      _ATELIER_PRO_ICONS=("🎨" "⚡" "🏆" "💰" "✨")
      _ATELIER_ICON_IDX=$(( ($(date +%s) / 5) % ${#_ATELIER_PRO_ICONS[@]} ))
      PLUGIN_LABEL="${_ATELIER_PRO_ICONS[$_ATELIER_ICON_IDX]} atelier"
      ;;
  esac
fi
export ATELIER_STATUS_SESSION_ID="${SESSION_ID:-}"
export ATELIER_STATUS_MODEL="${MODEL_ID:-${MODEL:-}}"
export ATELIER_STATUS_MODEL_DISPLAY="${MODEL:-}"
ATELIER_PY="$(bash "$(dirname "${BASH_SOURCE[0]}")/_atelier_python.sh" 2>/dev/null)"
ATELIER_PY="${ATELIER_PY:-python3}"

# --- Cost reset on /clear ---
# SessionStart(clear) drops two markers:
#   1. Session-keyed: statusline_cost_reset/<session_id>
#   2. Workspace-keyed: statusline_cost_reset/ws_<workspace_key>
# The workspace-keyed marker handles the case where /clear creates a new
# session_id: Claude Code fires SessionStart(clear) with the pre-clear id,
# but the statusline renders with the post-clear id, so the session-keyed
# marker would never be matched without this fallback.
if [ -n "${SESSION_ID:-}" ]; then
  _ATELIER_COST_RESET="${ATELIER_STATUS_ROOT}/statusline_cost_reset/${SESSION_ID}"
  _ATELIER_COST_BASE="${ATELIER_STATUS_ROOT}/statusline_cost_baseline/${SESSION_ID}"
  # Derive workspace key from TRANSCRIPT_PATH. Claude Code names its project
  # dirs by replacing every "/" in the cwd with "-"; the hook writes the
  # marker with the same encoding so we can match it here.
  _ATELIER_COST_RESET_WS=""
  if [ -n "${TRANSCRIPT_PATH:-}" ]; then
    _TR_DIR=$(dirname "${TRANSCRIPT_PATH}" 2>/dev/null || echo "")
    _TR_WS=$(basename "${_TR_DIR}" 2>/dev/null || echo "")
    # Subagent transcripts live one level deeper; skip past the subagents/ dir.
    if [ "${_TR_WS:-}" = "subagents" ]; then
      _TR_DIR=$(dirname "${_TR_DIR}" 2>/dev/null || echo "")
      _TR_WS=$(basename "${_TR_DIR}" 2>/dev/null || echo "")
    fi
    if [ -n "${_TR_WS:-}" ] && [ "${_TR_WS}" != "." ] && [ "${_TR_WS}" != "/" ]; then
      _ATELIER_COST_RESET_WS="${ATELIER_STATUS_ROOT}/statusline_cost_reset/ws_${_TR_WS}"
    fi
  fi
  if [ -f "${_ATELIER_COST_RESET}" ] || { [ -n "${_ATELIER_COST_RESET_WS:-}" ] && [ -f "${_ATELIER_COST_RESET_WS}" ]; }; then
    mkdir -p "${ATELIER_STATUS_ROOT}/statusline_cost_baseline" 2>/dev/null
    printf '%s' "${COST:-0}" >"${_ATELIER_COST_BASE}" 2>/dev/null
    rm -f "${_ATELIER_COST_RESET}" 2>/dev/null
    [ -n "${_ATELIER_COST_RESET_WS:-}" ] && rm -f "${_ATELIER_COST_RESET_WS}" 2>/dev/null
  fi
  if [ -f "${_ATELIER_COST_BASE}" ]; then
    _ATELIER_COST_BASE_VAL=$(cat "${_ATELIER_COST_BASE}" 2>/dev/null)
    COST=$(awk "BEGIN { d=${COST:-0}-${_ATELIER_COST_BASE_VAL:-0}; if (d<0) d=0; printf \"%.6f\", d }" 2>/dev/null || printf '%s' "${COST}")
  fi
fi

# --- ANSI colors ---
if [ -n "${ATELIER_NO_COLOR:-}" ]; then
  C_BRAND=""; C_PIPE=""; C_DIM=""; C_RESET=""
else
  C_BRAND=$'\033[1;38;2;168;85;247m'
  C_PIPE=$'\033[2;38;2;200;200;200m'
  C_DIM=$'\033[2;38;2;200;200;200m'
  C_RESET=$'\033[0m'
fi
PIPE="${C_PIPE}|${C_RESET}"
SEP="${C_DIM}/${C_RESET}"

# Live context occupancy (what fills the window now; drops after /compact).
LIVE_CTX_TOK=$(( ${IN_TOK:-0} + ${CACHE_R:-0} + ${CACHE_W:-0} ))
fmt_ctx() {
  local n=$1
  if [ "$n" -ge 1000000 ] 2>/dev/null; then
    local s=$(( n * 10 / 1000000 ))
    printf '%d.%dM' $(( s / 10 )) $(( s % 10 ))
  elif [ "$n" -ge 1000 ] 2>/dev/null; then
    printf '%dk' $(( n / 1000 ))
  else
    printf '%d' "$n"
  fi
}
ACTUAL_CTX_F=$(fmt_ctx "${LIVE_CTX_TOK}")

# --- Rotating dynamic segment from backend ---
# Export live cost + token counts so the backend can build frame 0.
export ATELIER_STATUSLINE_COST_USD="${COST:-0}"
export ATELIER_STATUSLINE_LIVE_IN_TOK="$(( ${IN_TOK:-0} + ${CACHE_W:-0} ))"
export ATELIER_STATUSLINE_LIVE_CACHE_TOK="${CACHE_R:-0}"
export ATELIER_STATUSLINE_LIVE_OUT_TOK="${OUT_TOK:-0}"
[ -n "${ATELIER_NO_COLOR:-}" ] && export ATELIER_STATUSLINE_NO_COLOR=1

_ATELIER_BIN="$(dirname "${ATELIER_PY}")/atelier"

# Dynamic segment: MCP sidecar (primary) → per-session subprocess cache (fallback).
# The MCP server writes sessions/<id>/statusline_frames (all frames, one per
# line) after every savings event using its window-anchored resolved session id
# — no subprocess, no session-id drift. Rotation is a wall-clock line pick, so
# frames keep rotating between writes. statusline_segment (single frame) is
# kept as the legacy fallback.
_NOW_S=$(date +%s)
# The canonical session dir is date+host partitioned
# (sessions/YYYY/MM/DD/<host>/<id>/ — see paths.session_dir); glob for it and
# keep the legacy flat path as a fallback for older stores. Newest mtime wins
# so a stale duplicate can never shadow the live segment; on equal mtimes the
# multi-frame file (listed first) wins.
_MCP_SIDECAR=""
_MCP_SIDECAR_MT=0
if [ -n "${SESSION_ID:-}" ]; then
  for _SC in "${ATELIER_STATUS_ROOT}/sessions/"*/*/*/*/"${SESSION_ID}/statusline_frames" \
             "${ATELIER_STATUS_ROOT}/sessions/${SESSION_ID}/statusline_frames" \
             "${ATELIER_STATUS_ROOT}/sessions/"*/*/*/*/"${SESSION_ID}/statusline_segment" \
             "${ATELIER_STATUS_ROOT}/sessions/${SESSION_ID}/statusline_segment"; do
    [ -f "${_SC}" ] || continue
    _SC_MT=$(stat -c '%Y' "${_SC}" 2>/dev/null || stat -f '%m' "${_SC}" 2>/dev/null || echo 0)
    if [ "${_SC_MT:-0}" -gt "${_MCP_SIDECAR_MT}" ]; then
      _MCP_SIDECAR="${_SC}"
      _MCP_SIDECAR_MT="${_SC_MT}"
    fi
  done
fi
# Per-session cache for the subprocess fallback path. Keyed strictly by the
# real SESSION_ID with NO "default" fallback: an empty id would collapse the
# key to one shared slot that every unbound window reads/writes, leaking one
# window's cost/savings into another. All reads/writes below are gated on a
# non-empty SESSION_ID, so when it is empty these names are never touched.
_SEG_CACHE="${ATELIER_STATUS_ROOT}/statusline_segment_cache_${SESSION_ID}"
_SEG_CACHE_TS="${ATELIER_STATUS_ROOT}/statusline_segment_ts_${SESSION_ID}"
DYNAMIC_SEG=""

# 1. MCP sidecar — fresh if written within 10s. The multi-frame file rotates
#    by wall clock (one frame per line, 5s per frame) so the display keeps
#    cycling even while the sidecar itself is not being rewritten.
if [ -n "${_MCP_SIDECAR}" ]; then
  _SIDECAR_AGE=$(( _NOW_S - ${_MCP_SIDECAR_MT:-0} ))
  if [ "${_SIDECAR_AGE}" -le 10 ]; then
    case "${_MCP_SIDECAR}" in
      *statusline_frames)
        _N_FRAMES=$(wc -l < "${_MCP_SIDECAR}" 2>/dev/null || echo 0)
        if [ "${_N_FRAMES:-0}" -gt 0 ] 2>/dev/null; then
          _FRAME_IDX=$(( (_NOW_S / 5) % _N_FRAMES + 1 ))
          DYNAMIC_SEG=$(sed -n "${_FRAME_IDX}p" "${_MCP_SIDECAR}" 2>/dev/null || true)
        fi
        ;;
      *)
        DYNAMIC_SEG=$(cat "${_MCP_SIDECAR}" 2>/dev/null || true)
        ;;
    esac
  fi
fi

# 2. Per-session subprocess cache — 8s TTL. Skipped entirely when SESSION_ID is
# empty (fail closed): the cache is a cross-window leak vector when unkeyed.
if [ -z "${DYNAMIC_SEG:-}" ] && [ -n "${SESSION_ID:-}" ]; then
  _CACHED_TS=$(cat "${_SEG_CACHE_TS}" 2>/dev/null || echo 0)
  _CACHE_AGE=$(( _NOW_S - ${_CACHED_TS:-0} ))
  if [ "${_CACHE_AGE}" -le 8 ] && [ -f "${_SEG_CACHE}" ]; then
    DYNAMIC_SEG=$(cat "${_SEG_CACHE}" 2>/dev/null || true)
  fi
fi

# 3. Subprocess fallback — spawns Python, result written to per-session cache
if [ -z "${DYNAMIC_SEG:-}" ]; then
  if [ -x "${_ATELIER_BIN}" ]; then
    DYNAMIC_SEG=$("${_ATELIER_BIN}" savings --segment 2>/dev/null)
  fi
  if [ -z "${DYNAMIC_SEG:-}" ]; then
    DYNAMIC_SEG=$(uv run --quiet atelier savings --segment 2>/dev/null)
  fi
  # Only cache when there is real live usage — avoids serving a stale
  # zero-token result to the next render that has actual tokens in context.
  # Persist only with a real SESSION_ID — never write a shared, unkeyed cache.
  if [ -n "${DYNAMIC_SEG:-}" ] && [ "${LIVE_CTX_TOK:-0}" -gt 0 ] && [ -n "${SESSION_ID:-}" ]; then
    # Atomic renames so a concurrent render never reads a torn cache file.
    printf '%s' "${DYNAMIC_SEG}" > "${_SEG_CACHE}.$$" 2>/dev/null \
      && mv -f "${_SEG_CACHE}.$$" "${_SEG_CACHE}" 2>/dev/null || true
    printf '%s' "${_NOW_S}" > "${_SEG_CACHE_TS}.$$" 2>/dev/null \
      && mv -f "${_SEG_CACHE_TS}.$$" "${_SEG_CACHE_TS}" 2>/dev/null || true
  fi
fi

# --- Background shell jobs ---
BG_JOBS=0
if [ -n "${TRANSCRIPT_PATH:-}" ] && [ -f "${TRANSCRIPT_PATH}" ]; then
  # Scope: THIS session's transcript + its own subagents/*.jsonl only. The
  # old dirname() fallback walked the whole project dir — every historical
  # session's transcript (100s of MB of awk) on every render.
  _BG_MAIN="${TRANSCRIPT_PATH}"
  case "${TRANSCRIPT_PATH}" in
    */subagents/*) _BG_MAIN="${TRANSCRIPT_PATH%/subagents/*}.jsonl" ;;
  esac
  _BG_SCAN_FILES=()
  [ -f "${_BG_MAIN}" ] && _BG_SCAN_FILES+=("${_BG_MAIN}")
  _BG_SUB_DIR="${_BG_MAIN%.jsonl}/subagents"
  if [ -d "${_BG_SUB_DIR}" ]; then
    while IFS= read -r -d '' _BG_F; do
      _BG_SCAN_FILES+=("${_BG_F}")
    done < <(find "${_BG_SUB_DIR}" -maxdepth 1 -type f -name '*.jsonl' -print0 2>/dev/null)
  fi
  if [ "${#_BG_SCAN_FILES[@]}" -eq 0 ]; then
    _BG_SCAN_FILES=("${TRANSCRIPT_PATH}")
  fi
  # Re-scan only when a scanned file changed; idle renders reuse the count.
  _BG_CACHE=""
  _BG_HIT=0
  _BG_SIG=$( (stat -c '%Y:%s' "${_BG_SCAN_FILES[@]}" 2>/dev/null || stat -f '%m:%z' "${_BG_SCAN_FILES[@]}" 2>/dev/null) | cksum | cut -d' ' -f1)
  if [ -n "${SESSION_ID:-}" ] && [ -n "${_BG_SIG:-}" ]; then
    # tmp, not ~/.atelier: the OS reclaims per-session cache files.
    _BG_CACHE_DIR="${TMPDIR:-/tmp}/atelier-statusline-$(id -u)"
    _BG_CACHE="${_BG_CACHE_DIR}/bgjobs_${SESSION_ID}"
    _BG_CACHED=$(cat "${_BG_CACHE}" 2>/dev/null || true)
    if [ -n "${_BG_CACHED}" ] && [ "${_BG_CACHED%%|*}" = "${_BG_SIG}" ]; then
      BG_JOBS="${_BG_CACHED##*|}"
      _BG_HIT=1
    fi
  fi
  [ "${_BG_HIT}" -eq 1 ] || BG_JOBS=$(awk '
    /tool_use_id/ && /Command running in background with ID: / {
      line = $0
      path = ""
      if (match(line, /Output is being written to: [^", ]+/)) {
        path = substr(line, RSTART, RLENGTH)
        sub(/^Output is being written to: /, "", path)
      }
      while (match(line, /Command running in background with ID: [a-z0-9]+/)) {
        id = substr(line, RSTART, RLENGTH)
        sub(/^.*ID: /, "", id)
        launched[id] = 1
        if (path != "") output_file[id] = path
        line = substr(line, RSTART + RLENGTH)
      }
    }
    /task-notification/ && match($0, /<task-id>[a-z0-9]+<\/task-id>/) {
      id = substr($0, RSTART, RLENGTH)
      gsub(/<\/?task-id>/, "", id)
      if ($0 ~ /<status>(completed|failed|stopped|cancelled|killed)<\/status>/) done[id] = 1
    }
    END {
      n = 0
      for (id in launched) {
        if (id in done) continue
        if (!(id in output_file)) continue
        cmd = "test -e \"" output_file[id] "\""
        if (system(cmd) != 0) continue
        n++
      }
      print n
    }
  ' "${_BG_SCAN_FILES[@]}" 2>/dev/null)
  [ -z "${BG_JOBS}" ] && BG_JOBS=0
  if [ "${_BG_HIT}" -eq 0 ] && [ -n "${_BG_CACHE}" ]; then
    # Atomic rename so a concurrent render never reads a torn cache file.
    mkdir -p "${_BG_CACHE_DIR}" 2>/dev/null || true
    printf '%s|%s' "${_BG_SIG}" "${BG_JOBS}" > "${_BG_CACHE}.$$" 2>/dev/null \
      && mv -f "${_BG_CACHE}.$$" "${_BG_CACHE}" 2>/dev/null || true
  fi
fi

# --- Background agents ---
BG_AGENTS=0
if [ -n "${SESSION_ID:-}" ]; then
  _NOW_EPOCH=$(date +%s)
  for _TASK_DIR in "${TMPDIR:-/tmp}/claude-$(id -u)"/*/${SESSION_ID}/tasks; do
    [ -d "${_TASK_DIR}" ] || continue
    for _TASK_LNK in "${_TASK_DIR}"/*.output; do
      [ -L "${_TASK_LNK}" ] || continue
      _TASK_MT=$(stat -L -c %Y "${_TASK_LNK}" 2>/dev/null || stat -L -f %m "${_TASK_LNK}" 2>/dev/null) || continue
      [ $(( _NOW_EPOCH - _TASK_MT )) -le 60 ] && BG_AGENTS=$(( BG_AGENTS + 1 ))
    done
    break
  done
fi

TASKS_SEG=""
[ "${BG_JOBS:-0}" -gt 0 ] 2>/dev/null && TASKS_SEG=" ${SEP} ${BG_JOBS} bg"
[ "${BG_AGENTS:-0}" -gt 0 ] 2>/dev/null && TASKS_SEG="${TASKS_SEG} ${SEP} ${BG_AGENTS} agent"

# --- Update tip: show once in the statusline when the plugin was upgraded ---
UPDATE_SEG=""
_UPDATE_STATE_FILE="${ATELIER_STATUS_ROOT}/update_state.json"
if [ -f "${_UPDATE_STATE_FILE}" ]; then
  _UPDATE_TIP=$(python3 -c "
import json, sys, pathlib
p = pathlib.Path(sys.argv[1])
try:
    d = json.loads(p.read_text())
    prev = d.get('previous_version', '')
    cur = d.get('current_version', '')
    if cur and prev and cur != prev and not d.get('notified'):
        print(prev + '|' + cur)
        d['notified'] = True
        p.write_text(json.dumps(d, indent=2))
except Exception:
    pass
" "${_UPDATE_STATE_FILE}" 2>/dev/null || true)
  if [ -n "${_UPDATE_TIP:-}" ]; then
    _TIP_PREV="${_UPDATE_TIP%%|*}"
    _TIP_CUR="${_UPDATE_TIP##*|}"
    UPDATE_SEG=" ${SEP} ${C_BRAND}updated v${_TIP_PREV}→${_TIP_CUR}${C_RESET}"
  fi
fi

# --- Staleness nudge: an installed OPTIONAL agent/skill unused for
# --stale-days (default 7, ATELIER_STALE_NUDGE_DAYS) is worth flagging for
# removal. Takes priority over the generic install tip below when present so
# the two never both render in the same frame. Same once-a-day marker-file
# cooldown as the update/install tips -- the token-cost lookup below spawns
# the CLI, so it only runs (at most) once per calendar day.
STALE_SEG=""
_TODAY=$(date +%F 2>/dev/null || echo "")
_ATELIER_STALE_MARKER="${ATELIER_STATUS_ROOT}/stale_nudge_shown_date"
if [ -n "${_TODAY}" ]; then
  _STALE_LAST=$(cat "${_ATELIER_STALE_MARKER}" 2>/dev/null || echo "")
  if [ "${_STALE_LAST}" != "${_TODAY}" ]; then
    mkdir -p "${ATELIER_STATUS_ROOT}" 2>/dev/null
    printf '%s' "${_TODAY}" > "${_ATELIER_STALE_MARKER}.$$" 2>/dev/null \
      && mv -f "${_ATELIER_STALE_MARKER}.$$" "${_ATELIER_STALE_MARKER}" 2>/dev/null || true
    _STALE_LINE=""
    if [ -x "${_ATELIER_BIN}" ]; then
      _STALE_LINE=$("${_ATELIER_BIN}" stale-nudge --host claude 2>/dev/null | head -n1)
    fi
    if [ -z "${_STALE_LINE:-}" ]; then
      _STALE_LINE=$(uv run --quiet atelier stale-nudge --host claude 2>/dev/null | head -n1)
    fi
    if [ -n "${_STALE_LINE:-}" ]; then
      IFS='|' read -r _S_KIND _S_NAME _S_DAYS _S_COST <<<"${_STALE_LINE}"
      _S_UNUSED="unused ${_S_DAYS}d"
      [ -z "${_S_DAYS:-}" ] && _S_UNUSED="never used"
      STALE_SEG=" ${SEP} ${C_DIM}${_S_NAME} installed, ${_S_UNUSED} -- /atelier remove ${_S_NAME} (~${_S_COST} tok/turn)${C_RESET}"
    fi
  fi
fi

# --- Optional-install tip: surface the install-more-agents/skills interface ---
# Atelier ships a bare-minimum default (agent: code, no extra skills); explore,
# plan, execute, review, research, solve, and the public skills are opt-in via
# `/atelier install <name>` (or `atelier agent/skill install <name>` from a
# shell). Shown at most once per calendar day, same file-marker pattern as the
# update tip above, so it stays a passive reminder rather than a repeated nag.
# Suppressed for a render where the staleness nudge above already fired.
TIP_SEG=""
_ATELIER_TIP_MARKER="${ATELIER_STATUS_ROOT}/agent_install_tip_shown_date"
if [ -z "${STALE_SEG:-}" ] && [ -n "${_TODAY}" ]; then
  _TIP_LAST=$(cat "${_ATELIER_TIP_MARKER}" 2>/dev/null || echo "")
  if [ "${_TIP_LAST}" != "${_TODAY}" ]; then
    TIP_SEG=" ${SEP} ${C_DIM}more agents/skills: /atelier install <name>${C_RESET}"
    mkdir -p "${ATELIER_STATUS_ROOT}" 2>/dev/null
    printf '%s' "${_TODAY}" > "${_ATELIER_TIP_MARKER}.$$" 2>/dev/null \
      && mv -f "${_ATELIER_TIP_MARKER}.$$" "${_ATELIER_TIP_MARKER}" 2>/dev/null || true
  fi
fi

printf '%s%s%s %s %s ctx %s %s%%%s%s%s%s%s\n' \
  "$C_BRAND" "$PLUGIN_LABEL" "$C_RESET" \
  "$PIPE" "$MODEL" "$ACTUAL_CTX_F" "$PCT_INT" \
  "${DYNAMIC_SEG}" "$TASKS_SEG" "${UPDATE_SEG}" "${STALE_SEG}" "${TIP_SEG}"
