#!/usr/bin/env python3
"""Render canonical Atelier mode docs into host agent and skill surfaces."""

from __future__ import annotations

import argparse
import difflib
import json
import os
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
MODES_DIR = ROOT / "docs" / "agent-os" / "modes"
HOST_SKILL_DIRS = {
    "claude": ROOT / "integrations" / "claude" / "plugin" / "skills",
    "codex": ROOT / "integrations" / "codex" / "plugin" / "skills",
    "antigravity": ROOT / "integrations" / "antigravity" / "skills",
}


@dataclass(frozen=True)
class ModeDoc:
    name: str
    skill_description: str
    agent_description: str
    body: str
    source_path: Path

    @property
    def title(self) -> str:
        return self.name.replace("-", " ").title()


def relpath(output_path: Path, target: Path) -> str:
    return os.path.relpath(target, output_path.parent)


def generated_notice(output_path: Path, source_path: Path) -> str:
    source = relpath(output_path, source_path)
    return f"<!-- Generated by `scripts/render_mode_surfaces.py`. Edit `{source}` and rerun the generator. -->"


def parse_frontmatter(text: str) -> tuple[dict[str, str], str]:
    if not text.startswith("---\n"):
        raise ValueError("mode doc is missing frontmatter")
    end = text.find("\n---\n", 4)
    if end < 0:
        raise ValueError("mode doc frontmatter is not terminated")
    raw_meta = text[4:end].splitlines()
    meta: dict[str, str] = {}
    for raw_line in raw_meta:
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if ":" not in line:
            raise ValueError(f"invalid frontmatter line: {raw_line}")
        key, value = line.split(":", 1)
        meta[key.strip()] = value.strip().strip('"').strip("'")
    body = text[end + len("\n---\n") :].lstrip()
    return meta, body


def load_modes() -> dict[str, ModeDoc]:
    modes: dict[str, ModeDoc] = {}
    for path in sorted(MODES_DIR.glob("*.md")):
        meta, body = parse_frontmatter(path.read_text(encoding="utf-8"))
        name = meta["mode"]
        modes[name] = ModeDoc(
            name=name,
            skill_description=meta["skill_description"],
            agent_description=meta["agent_description"],
            body=body.rstrip() + "\n",
            source_path=path,
        )
    return modes


def _format_frontmatter_value(value: Any) -> str:
    if isinstance(value, list):
        return json.dumps(value)
    if isinstance(value, bool):
        return "true" if value else "false"
    return str(value)


def render_frontmatter(items: list[tuple[str, Any]]) -> str:
    lines = ["---"]
    for key, value in items:
        lines.append(f"{key}: {_format_frontmatter_value(value)}")
    lines.append("---")
    return "\n".join(lines)


CLAUDE_STABLE_FRONTMATTER: dict[str, list[tuple[str, Any]]] = {
    "code": [("name", "code"), ("description", ""), ("tools", ["*"]), ("color", "purple")],
    "explore": [
        ("name", "explore"),
        ("description", ""),
        (
            "tools",
            [
                "Read",
                "Grep",
                "Glob",
                "mcp__atelier__context",
                "mcp__atelier__search",
                "mcp__atelier__read",
                "mcp__atelier__memory",
            ],
        ),
        ("disallowedTools", ["Edit", "Write", "MultiEdit", "NotebookEdit", "Agent"]),
        ("color", "blue"),
        ("model", "haiku"),
    ],
    "review": [
        ("name", "review"),
        ("description", ""),
        (
            "tools",
            [
                "Read",
                "Grep",
                "Glob",
                "mcp__atelier__context",
                "mcp__atelier__read",
                "mcp__atelier__search",
                "mcp__atelier__verify",
                "mcp__atelier__trace",
                "mcp__atelier__memory",
            ],
        ),
        ("color", "yellow"),
    ],
    "repair": [("name", "repair"), ("description", ""), ("tools", ["*"]), ("color", "red")],
    "research": [
        ("name", "research"),
        ("description", ""),
        (
            "tools",
            [
                "WebFetch",
                "WebSearch",
                "mcp__atelier__context",
                "mcp__atelier__search",
                "mcp__atelier__read",
                "mcp__atelier__memory",
            ],
        ),
        ("color", "green"),
    ],
}

CLAUDE_DEV_FRONTMATTER: dict[str, list[tuple[str, Any]]] = {
    "code": [
        ("name", "code"),
        ("description", ""),
        ("tools", ["*"]),
        ("disallowedTools", ["Read", "Edit", "Write", "Grep", "Glob", "NotebookEdit"]),
        ("color", "purple"),
    ],
    "explore": [
        ("name", "explore"),
        ("description", ""),
        ("color", "cyan"),
        ("model", "haiku"),
        (
            "tools",
            [
                "Read",
                "Grep",
                "Glob",
                "WebFetch",
                "mcp__atelier__context",
                "mcp__atelier__search",
                "mcp__atelier__read",
                "mcp__atelier__memory",
            ],
        ),
        ("disallowedTools", ["Edit", "Write", "MultiEdit", "NotebookEdit", "mcp__atelier__edit", "Agent"]),
    ],
    "review": [
        ("name", "review"),
        ("description", ""),
        (
            "tools",
            [
                "Read",
                "Grep",
                "Glob",
                "mcp__atelier__context",
                "mcp__atelier__read",
                "mcp__atelier__search",
                "mcp__atelier__verify",
                "mcp__atelier__trace",
                "mcp__atelier__memory",
            ],
        ),
        ("color", "yellow"),
    ],
    "repair": [("name", "repair"), ("description", ""), ("tools", ["*"]), ("color", "red")],
    "research": [
        ("name", "research"),
        ("description", ""),
        (
            "tools",
            [
                "WebFetch",
                "WebSearch",
                "mcp__atelier__context",
                "mcp__atelier__search",
                "mcp__atelier__read",
                "mcp__atelier__memory",
            ],
        ),
        ("color", "green"),
    ],
}

OPENCODE_FRONTMATTER: dict[str, list[tuple[str, Any]]] = {
    "code": [("description", "Atelier - main coding agent for the Agent Reasoning Runtime"), ("mode", "primary")],
    "explore": [("description", "Read-only codebase explorer. Finds files, symbols, and patterns. Never edits.")],
    "review": [
        ("description", "Adversarial code reviewer. Applies the verification ladder. Never edits source files.")
    ],
    "repair": [
        (
            "description",
            "Repair specialist for repeated failures. Captures the failing signal, calls rescue, applies the fix, and records a postmortem.",
        )
    ],
    "research": [
        (
            "description",
            "External researcher. Fetches web pages, GitHub repos, and package docs. Never edits. Produces a structured memo with citations.",
        )
    ],
}

ANTIGRAVITY_FRONTMATTER: dict[str, list[tuple[str, Any]]] = {
    "code": [
        (
            "description",
            "Main Atelier coding agent. Uses Atelier MCP tools for all file I/O, search, edits, and shell work.",
        )
    ],
    "explore": [("description", "Read-only codebase explorer. Finds files, symbols, and patterns. Never edits.")],
    "review": [
        ("description", "Adversarial code reviewer. Applies the verification ladder. Never edits source files.")
    ],
    "repair": [
        (
            "description",
            "Repair specialist for repeated failures. Captures the failing signal, calls rescue, applies the fix, and records a postmortem.",
        )
    ],
    "research": [
        (
            "description",
            "External researcher. Fetches web pages, GitHub repos, and package docs. Never edits. Produces a structured memo with citations.",
        )
    ],
}


def _inject_description(frontmatter: list[tuple[str, Any]], description: str) -> list[tuple[str, Any]]:
    rendered: list[tuple[str, Any]] = []
    for key, value in frontmatter:
        rendered.append((key, description if key == "description" and value == "" else value))
    return rendered


def render_skill(mode: ModeDoc, output_path: Path) -> str:
    return (
        "\n".join(
            [
                render_frontmatter([("name", mode.name), ("description", mode.skill_description)]),
                "",
                generated_notice(output_path, mode.source_path),
                "",
                mode.body.rstrip(),
            ]
        ).rstrip()
        + "\n"
    )


def render_claude_agent(mode: ModeDoc, output_path: Path, *, dev: bool) -> str:
    template = CLAUDE_DEV_FRONTMATTER if dev else CLAUDE_STABLE_FRONTMATTER
    frontmatter = _inject_description(template[mode.name], mode.agent_description)
    identity_block = ["You are operating as *atelier:code*.", ""] if mode.name == "code" else []
    return (
        "\n".join(
            [
                render_frontmatter(frontmatter),
                "",
                generated_notice(output_path, mode.source_path),
                "",
                *identity_block,
                mode.body.rstrip(),
            ]
        ).rstrip()
        + "\n"
    )


def render_simple_agent(mode: ModeDoc, output_path: Path, *, frontmatter_map: dict[str, list[tuple[str, Any]]]) -> str:
    frontmatter = frontmatter_map[mode.name]
    identity_block = ["You are operating as *atelier:code*.", ""] if mode.name == "code" else []
    return (
        "\n".join(
            [
                render_frontmatter(frontmatter),
                "",
                generated_notice(output_path, mode.source_path),
                "",
                *identity_block,
                mode.body.rstrip(),
            ]
        ).rstrip()
        + "\n"
    )


def build_mode_outputs(root: Path | None = None) -> dict[Path, str]:
    repo_root = ROOT if root is None else root
    modes = load_modes()
    outputs: dict[Path, str] = {}

    for mode in modes.values():
        skill_path = repo_root / "integrations" / "skills" / mode.name / "SKILL.md"
        skill_content = render_skill(mode, skill_path)
        outputs[skill_path] = skill_content
        for host_dir in HOST_SKILL_DIRS.values():
            host_skill_path = host_dir / mode.name / "SKILL.md"
            outputs[host_skill_path] = skill_content

        stable_path = repo_root / "integrations" / "claude" / "plugin" / "agents" / f"{mode.name}.md"
        outputs[stable_path] = render_claude_agent(mode, stable_path, dev=False)
        dev_path = repo_root / "integrations" / "claude" / "plugin" / "agents" / f"{mode.name}.dev.md"
        outputs[dev_path] = render_claude_agent(mode, dev_path, dev=True)

        antigravity_name = "atelier-code.md" if mode.name == "code" else f"atelier-{mode.name}.md"
        antigravity_path = repo_root / "integrations" / "antigravity" / "plugin" / "agents" / antigravity_name
        outputs[antigravity_path] = render_simple_agent(mode, antigravity_path, frontmatter_map=ANTIGRAVITY_FRONTMATTER)

        opencode_name = "atelier.md" if mode.name == "code" else f"{mode.name}.md"
        opencode_path = repo_root / "integrations" / "opencode" / "agents" / opencode_name
        outputs[opencode_path] = render_simple_agent(mode, opencode_path, frontmatter_map=OPENCODE_FRONTMATTER)

    return outputs


def write_or_diff(path: Path, expected: str, *, check: bool) -> bool:
    current = path.read_text(encoding="utf-8") if path.exists() else ""
    if current == expected:
        return False
    if check:
        diff = difflib.unified_diff(
            current.splitlines(),
            expected.splitlines(),
            fromfile=str(path),
            tofile=f"{path} (generated)",
            lineterm="",
        )
        sys.stdout.write("\n".join(diff) + "\n")
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(expected, encoding="utf-8")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated outputs differ")
    args = parser.parse_args()

    changed = False
    for path, content in build_mode_outputs().items():
        changed = write_or_diff(path, content, check=args.check) or changed

    if args.check and changed:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
