#!/usr/bin/env python3
"""Generate host instruction surfaces from the live Agent OS docs."""

from __future__ import annotations

import argparse
import difflib
import os
import sys
from pathlib import Path

import yaml
from render_mode_surfaces import build_mode_outputs

ROOT = Path(__file__).resolve().parents[1]

DOC_LINKS = [
    ("Agent OS", ROOT / "docs/agent-os/README.md"),
    ("Workflow", ROOT / "docs/agent-os/workflow.md"),
    ("Taste invariants", ROOT / "docs/agent-os/taste-invariants.md"),
    ("Validation matrix", ROOT / "docs/agent-os/validation-matrix.md"),
    ("Architecture", ROOT / "docs/architecture/README.md"),
    ("Quality scorecard", ROOT / "docs/quality/scorecard.md"),
    ("Plans", ROOT / "docs/plans/README.md"),
    ("Decisions", ROOT / "docs/decisions/README.md"),
]

HOST_FALLBACKS = {
    "copilot": "Copilot or VS Code native file reads, workspace search, shell `rg`, or `grep`",
    "antigravity": "Antigravity or agy native file reads, workspace search, shell `rg`, or `grep`",
    "claude": "Claude-native file tools, Grep/Glob, shell `rg`, or `grep`",
    "codex": "native Codex file reads, shell `rg`, `grep`, or direct repository search",
    "opencode": "opencode-native file reads, repository search, shell `rg`, or `grep`",
    "cursor": "Cursor or VS Code native file reads, workspace search, shell `rg`, or `grep`",
    "hermes": "native Hermes file tools, shell `rg`, `grep`, or direct repository search",
}

HOST_DISPLAY = {
    "antigravity": "Antigravity",
    "copilot": "Copilot",
    "claude": "Claude",
    "codex": "Codex",
    "opencode": "OpenCode",
    "cursor": "Cursor",
    "hermes": "Hermes",
}

SESSION_TEMPLATE = (
    "Atelier budget optimizer is active for {host}.\n"
    "Use Atelier MCP tools first for file I/O, search, edits, and shell work.\n"
    "Always prefer Atelier MCP tools for file I/O, search, edits, shell, and code-intel work.\n"
    "Use native host tools only when Atelier returns `noop`, is hidden, or is unavailable.\n"
    "Before changing files, name the deliverable and summarize the smallest viable plan.\n"
    "Keep context narrow: use only the current goal, relevant files, failing command/output, and known constraints.\n"
    "Restate working context in under 10 bullets before editing or after compaction.\n"
    "If more than 10 minutes pass without an edit, name the expected deliverable or check with the user.\n"
    "If the same approach fails twice, call rescue or change approach; do not retry a third time.\n"
)


def relpath(output_path: Path, target: Path) -> str:
    return os.path.relpath(target, output_path.parent)


def generated_notice(output_path: Path) -> str:
    source = relpath(output_path, ROOT / "docs/agent-os/README.md")
    return f"<!-- Generated by `scripts/sync_agent_context.py`. Edit `{source}` and rerun the generator. -->"


def doc_links(output_path: Path) -> str:
    return "\n".join(f"- [{label}]({relpath(output_path, target)})" for label, target in DOC_LINKS)


def budget_section() -> str:
    return "\n".join(
        [
            "## Budget optimizer",
            "",
            "- Before changing files, name the deliverable and summarize the smallest viable plan.",
            "- Keep context narrow: use only the current goal, relevant files, failing command/output, and known constraints.",
            "- Restate working context in under 10 bullets before editing or after compaction.",
            "- If more than 10 minutes pass without an edit, name the expected deliverable or check with the user.",
            "- If the same approach fails twice, call `rescue` or change approach; do not retry a third time.",
        ]
    )


def fallback_section(host: str) -> str:
    return "\n".join(
        [
            "## Native fallback",
            "",
            f"If an Atelier MCP tool returns `noop`, is hidden, or is unavailable, use {HOST_FALLBACKS[host]}.",
            "Always return findings instead of waiting for tool availability to improve.",
        ]
    )


def validation_line(output_path: Path) -> str:
    matrix = relpath(output_path, ROOT / "docs/agent-os/validation-matrix.md")
    return f"See [Validation matrix]({matrix}) for the minimum checks by change surface."


def coding_guidelines_section() -> str:
    """Behavioral coding guidelines — fully inlined, no external doc links. https://github.com/multica-ai/andrej-karpathy-skills"""

    return """
## Coding Guidelines
Behavioral guidelines to reduce common LLM coding mistakes. Merge with project-specific instructions as needed.

**Tradeoff:** These guidelines bias toward caution over speed. For trivial tasks, use judgment.

### 1. Think Before Coding

**Don't assume. Don't hide confusion. Surface tradeoffs.**

Before implementing:
- State your assumptions explicitly. If uncertain, ask.
- If multiple interpretations exist, present them - don't pick silently.
- If a simpler approach exists, say so. Push back when warranted.
- If something is unclear, stop. Name what's confusing. Ask.

### 2. Simplicity First

**Minimum code that solves the problem. Nothing speculative.**

- No features beyond what was asked.
- No abstractions for single-use code.
- No "flexibility" or "configurability" that wasn't requested.
- No error handling for impossible scenarios.
- If you write 200 lines and it could be 50, rewrite it.

Ask yourself: "Would a senior engineer say this is overcomplicated?" If yes, simplify.

### 3. Surgical Changes

**Touch only what you must. Clean up only your own mess.**

When editing existing code:
- Don't "improve" adjacent code, comments, or formatting.
- Don't refactor things that aren't broken.
- Match existing style, even if you'd do it differently.
- If you notice unrelated dead code, mention it - don't delete it.

When your changes create orphans:
- Remove imports/variables/functions that YOUR changes made unused.
- Don't remove pre-existing dead code unless asked.

The test: Every changed line should trace directly to the user's request.

### 4. Goal-Driven Execution

**Define success criteria. Loop until verified.**

Transform tasks into verifiable goals:
- "Add validation" → "Write tests for invalid inputs, then make them pass"
- "Fix the bug" → "Write a test that reproduces it, then make it pass"
- "Refactor X" → "Ensure tests pass before and after"

For multi-step tasks, state a brief plan:
```
1. [Step] → verify: [check]
2. [Step] → verify: [check]
3. [Step] → verify: [check]
```

Strong success criteria let you loop independently. Weak criteria ("make it work") require constant clarification.

---

**These guidelines are working if:** fewer unnecessary changes in diffs, fewer rewrites due to overcomplication, and clarifying questions come before implementation rather than after mistakes.
"""


def tool_substitution_table() -> str:
    """Inline substitution table — baked into every host file so agents can't miss it."""
    return "\n".join(
        [
            "## Tool substitution — mandatory",
            "",
            "| Use this | Instead of | Why |",
            "|---|---|---|",
            "| `mcp__atelier__read` | `Read` / `Bash(cat ...)` | outline-first, 80-95% fewer tokens on large files |",
            "| `mcp__atelier__search` | `Grep` / `Glob` / `Bash(grep/rg ...)` | ranked, budget-capped, ~280k tokens saved vs naive scan |",
            "| `mcp__atelier__edit` | `Edit` / `Write` | atomic multi-file, snapshot/rollback, diff recorded |",
            "| `mcp__atelier__shell` | `Bash(...)` | ANSI-stripped, line-truncated, token-compact |",
            "| `mcp__atelier__code op=files` | `find` / `glob` inventory loops | indexed file tree without filesystem scans |",
            "| `mcp__atelier__code op=search` | `Bash(grep -rn symbol ...)` | SCIP-indexed, zero subprocess cost |",
            "",
            "**Bash is only for git commands and process management.** "
            "Do NOT use `Bash(cat file)`, `Bash(grep ...)`, or `Bash(find ...)` "
            "— use the atelier equivalents above.",
        ]
    )


def mcp_priority_section() -> str:
    """Always prefer Atelier MCP tools — positive framing, no comparisons."""
    return "\n".join(
        [
            "## Always prefer Atelier MCP tools",
            "",
            "Always prefer Atelier MCP tools for file I/O, search, edits, shell commands, and",
            "code intelligence. Native tools are fallback-only.",
            "",
            "| Atelier tool | Best for |",
            "|---|---|",
            "| `mcp__atelier__code` (all ops) | Code intelligence: symbol search, definitions, callers/callees, impact, file tree, routes, context |",
            "| `mcp__atelier__grep` | Regex and glob search across files |",
            "| `mcp__atelier__read` | Reading files (outline mode for large files) |",
            "| `mcp__atelier__edit` | Editing files (atomic multi-file with rollback) |",
            "| `mcp__atelier__search` | Ranked semantic search |",
            "| `mcp__atelier__shell` | Shell commands (ANSI-stripped, token-compact output) |",
            "",
            "**Decision rules:**",
            "",
            "1. **Symbol lookup, definition, callers, callees, impact, file tree, routes, context** → `mcp__atelier__code` FIRST.",
            "2. **Regex/grep, text search** → `mcp__atelier__grep` FIRST.",
            "3. **File reading** → `mcp__atelier__read` FIRST.",
            "4. **Editing** → `mcp__atelier__edit` FIRST.",
            "5. **Shell commands** → `mcp__atelier__shell` FIRST.",
            "",
            "**Fallback:** Use native host tools only when the Atelier equivalent returns `noop`, is hidden, or is unavailable.",
        ]
    )


def implement_line(output_path: Path) -> str:
    tool_sub_link = relpath(output_path, ROOT / "docs/agent-os/tool-substitution.md")
    return (
        "2. **Implement**: Use Atelier MCP tools for file I/O, search, edits, and shell work "
        f"(see [Tool substitution]({tool_sub_link})). Use native host tools only when Atelier "
        "returns `noop`, is hidden, or is unavailable. Use `route` or `rescue` when the same "
        "approach fails twice."
    )


def render_project_entrypoint(output_path: Path, *, title: str, host: str | None = None) -> str:
    tool_sub_link = relpath(output_path, ROOT / "docs/agent-os/tool-substitution.md")
    lines = [
        generated_notice(output_path),
        "",
        f"# {title}",
        "",
        "This file is a thin entrypoint. The live source of truth lives in the linked docs tree:",
        "",
        doc_links(output_path),
        "",
        "## Operating loop",
        "",
        "1. **Context** — call `mcp__atelier__context` with `task`, `files`, `domain` before touching any file.",
        "2. **Implement** — use Atelier tools for ALL file I/O and shell ops "
        f"(see [Tool substitution]({tool_sub_link})). Use `route` to get model recommendations "
        "before expensive steps. Use `rescue` on repeated failures.",
        "3. **Record** — call `mcp__atelier__trace` at completion.",
        "",
        tool_substitution_table(),
        "",
        mcp_priority_section(),
        "",
        "## Project-specific invariants",
        "",
        "- Verify source-of-truth files before coding instead of guessing shapes.",
        "- Keep root host files short and move durable rules into `docs/agent-os/`.",
        "- Use the validation matrix before concluding the task.",
        "- Promote durable process changes into plans, decisions, or generated host artifacts.",
        "",
        budget_section(),
        "",
        coding_guidelines_section(),
    ]
    if host:
        lines.extend(["", fallback_section(host)])
    lines.extend(["", "## Validation", "", validation_line(output_path)])
    body = "\n".join(lines).rstrip() + "\n"
    if output_path == ROOT / "AGENTS.md":
        return "\n".join(["<!-- ATELIER:CODE START -->", body.rstrip(), "<!-- ATELIER:CODE END -->"]) + "\n"
    return body


def render_copilot_body(output_path: Path) -> str:
    """Thin in-repo version — for .github/copilot-instructions.md where docs/ exists."""
    tool_sub_link = relpath(output_path, ROOT / "docs/agent-os/tool-substitution.md")
    return (
        "\n".join(
            [
                generated_notice(output_path),
                "",
                "## Atelier - Copilot Instructions",
                "",
                "Use the Atelier 3-step process for every task:",
                "1. **Context**: call `context` with the task, domain, and tools.",
                f"2. **Implement**: use Atelier MCP tools for file I/O, search, edits, and shell work "
                f"(see [Tool substitution]({tool_sub_link})). Use native Copilot or VS Code tools only when Atelier returns `noop`, is hidden, or is unavailable. "
                "Use `route` or `rescue` when needed.",
                "3. **Record**: call `record` when the work is done.",
                "",
                tool_substitution_table(),
                "",
                mcp_priority_section(),
                "",
                "Treat this file as a thin entrypoint. The live source of truth is:",
                "",
                doc_links(output_path),
                "",
                budget_section(),
                "",
                fallback_section("copilot"),
                "",
                "## Validation",
                "",
                f"{validation_line(output_path)} Use the VS Code tasks for repeatable preflight, worktree, and runtime evidence loops.",
            ]
        ).rstrip()
        + "\n"
    )


def render_copilot_user_surface(output_path: Path) -> str:
    """Self-contained user-repo version — no relative doc links, coding guidelines inlined."""
    return (
        "\n".join(
            [
                generated_notice(output_path),
                "",
                "## Atelier - Copilot Instructions",
                "",
                "Use the Atelier 3-step process for every task:",
                "1. **Context**: call `context` with the task, domain, and tools.",
                "2. **Implement**: use Atelier MCP tools for file I/O, search, edits, and shell work "
                "(see Tool substitution table below). "
                "Use native Copilot or VS Code tools only when Atelier returns `noop`, is hidden, or is unavailable. "
                "Use `route` or `rescue` when needed.",
                "3. **Record**: call `record` when the work is done.",
                "",
                tool_substitution_table(),
                "",
                mcp_priority_section(),
                "",
                budget_section(),
                "",
                coding_guidelines_section(),
                "",
                fallback_section("copilot"),
                "",
                "## Validation",
                "",
                "See the validation matrix for the minimum checks by change surface. Use the VS Code tasks for repeatable preflight, worktree, and runtime evidence loops.",
            ]
        ).rstrip()
        + "\n"
    )


def render_copilot_workspace(output_path: Path) -> str:
    body = render_copilot_body(output_path)
    return "\n".join(["---", 'applyTo: "**"', "---", "", body]).rstrip() + "\n"


def render_chatmode(output_path: Path) -> str:
    return (
        "\n".join(
            [
                "---",
                'description: "Atelier - Agent Reasoning Runtime coding agent"',
                "tools:",
                "  [",
                '    "codebase",',
                '    "changes",',
                '    "editFiles",',
                '    "fetch",',
                '    "findTestFiles",',
                '    "githubRepo",',
                '    "problems",',
                '    "runCommands",',
                '    "runTasks",',
                '    "runTests",',
                '    "search",',
                '    "searchResults",',
                '    "terminalLastCommand",',
                '    "terminalSelection",',
                '    "testFailure",',
                '    "usages",',
                '    "vscodeAPI",',
                "  ]",
                "---",
                "",
                generated_notice(output_path),
                "",
                "# atelier:code",
                "",
                "You are operating as *atelier:code*.",
                "",
                "## Operating loop",
                "",
                "1. **Context** - call MCP tool `context` with task, domain, files, and tools.",
                "2. **Plan** - keep the plan small and concrete.",
                "3. **Execute** - use Atelier MCP tools for file I/O, search, edits, and shell work. "
                "Use native Copilot or VS Code tools only when Atelier returns `noop`, is hidden, or is unavailable.",
                "4. **Recover** - call `rescue` after two failed attempts.",
                "5. **Record** - call `record` with the observable result.",
                "",
                budget_section(),
                "",
                fallback_section("copilot"),
            ]
        ).rstrip()
        + "\n"
    )


def render_claude_code_agent(output_path: Path) -> str:
    return (
        "\n".join(
            [
                "---",
                "name: code",
                "description: Main coding agent. Edits, refactors, fixes bugs, and ships features. Uses the Atelier task loop for planning and validation.",
                'tools: ["*"]',
                "color: purple",
                "---",
                "",
                generated_notice(output_path),
                "",
                "# Atelier Code Agent",
                "",
                "You are the **main coding agent**. The Atelier MCP server is wired in as `atelier`.",
                "",
                "## Operating loop",
                "",
                "1. **Context**: Call `context` with `task`, `files`, `domain`, and `errors`.",
                "2. **Implement**: Use Atelier MCP tools for file I/O, search, edits, and shell work."
                " Use Claude-native tools only when Atelier returns `noop`, is hidden, or is unavailable.",
                '3. **Record**: Call `record` at completion with `agent: "atelier:code"`.',
                "",
                mcp_priority_section(),
                "",
                budget_section(),
                "",
                coding_guidelines_section(),
                "",
                fallback_section("claude"),
            ]
        ).rstrip()
        + "\n"
    )


def render_claude_review_agent(output_path: Path) -> str:
    return (
        "\n".join(
            [
                "---",
                "name: review",
                "description: Adversarial code reviewer. Applies the verification ladder and rubric discipline. Never edits source files.",
                'tools: ["Read", "Grep", "Glob", "mcp__atelier__context", "mcp__atelier__read", "mcp__atelier__search", "mcp__atelier__verify", "mcp__atelier__trace", "mcp__atelier__memory"]',
                "color: yellow",
                "---",
                "",
                generated_notice(output_path),
                "",
                "# Atelier Review Agent",
                "",
                "You are the **adversarial reviewer**. Your job is to find what is wrong, not to validate that work was done.",
                "",
                "## Operating loop",
                "",
                "1. **Read** the files in scope, preferring `mcp__atelier__read` and `mcp__atelier__search` before native Read/Grep/Glob. Never trust summaries — verify the code directly.",
                "2. **Apply the verification ladder**: existence → substantive → wired → data flow.",
                "3. **Report findings**: every finding must have a severity (Blocker|Warning), `file:line`, and a concrete fix.",
                '4. **Verify** — call `verify(rubric_id="rubric_code_review", checks={{...}})` before concluding.',
                '5. **Record** — call `record` with `agent: "atelier:review"`. Include learnings for any surprise or lesson.',
                "",
                "## Hard rules",
                "",
                "- **Never edit source files.** Read only.",
                "- Every finding must carry Blocker or Warning. Unlabelled findings are invalid output.",
                "- Every Blocker must include `file:line` and a concrete fix snippet.",
                "- Do not flag style preferences as Blocker or Warning.",
                "- `status: skipped` (nothing to review) ≠ `status: clean` (reviewed, no issues).",
                "",
                fallback_section("claude"),
            ]
        ).rstrip()
        + "\n"
    )


def render_claude_explore_agent(output_path: Path) -> str:
    return (
        "\n".join(
            [
                "---",
                "name: explore",
                "description: Read-only codebase explorer. Finds files, symbols, and patterns. Never edits.",
                'tools: ["Read", "Grep", "Glob", "mcp__atelier__context", "mcp__atelier__search", "mcp__atelier__read", "mcp__atelier__memory"]',
                'disallowedTools: ["Edit", "Write", "MultiEdit", "NotebookEdit", "Agent"]',
                "color: blue",
                "model: haiku",
                "---",
                "",
                generated_notice(output_path),
                "",
                "# Atelier Explore Agent",
                "",
                "You are the **read-only explorer**. Locate, read, and report. Never edit, create, or delete files.",
                "",
                "## Operating loop",
                "",
                "1. **Context**: Call `context` with `task`, `files`, and `domain` to surface relevant ReasonBlocks.",
                "2. **Search**: Prefer `mcp__atelier__search` and `mcp__atelier__read`; use Grep, Glob, or Read only as fallback.",
                "3. **Report**: Return findings immediately. Do not wait for tools to become available.",
                "",
                mcp_priority_section(),
                "",
                "## Hard rules",
                "",
                "- **Never edit, write, or delete files.**",
                "- Stay within 12 tool calls per task — prioritize breadth over depth.",
                "- Return findings even when partial — partial coverage beats silence.",
                "- If the first search path is wrong, try an alternative before giving up.",
                "",
                fallback_section("claude"),
            ]
        ).rstrip()
        + "\n"
    )


def render_claude_repair_agent(output_path: Path) -> str:
    return (
        "\n".join(
            [
                "---",
                "name: repair",
                "description: Repair specialist for repeated failures. Captures the failing signal, calls rescue, applies the fix, records a postmortem.",
                'tools: ["*"]',
                "color: red",
                "---",
                "",
                generated_notice(output_path),
                "",
                "# Atelier Repair Agent",
                "",
                "You are the **repair specialist**. Activate when the same approach has failed twice.",
                "",
                "## Operating loop",
                "",
                "1. **Capture** the exact failing signal: command output, error text, file and line.",
                "2. **Rescue** — call `rescue` with the error and recent actions. Apply the recommendation exactly.",
                "3. **Validate** — run the narrowest command that would prove the fix worked.",
                "4. **Escalate** — if the same failure persists after the rescue, stop and report. Do not retry a third time.",
                '5. **Verify** — call `verify(rubric_id="rubric_debugging_task", checks={...})` before concluding:',
                "   - `failing_signal_captured` — exact error text was collected before acting",
                "   - `repeated_failure_loop_avoided` — did not retry the same fix a third time",
                "   - `new_hypothesis_stated` — rescue produced a different hypothesis than what failed",
                "   - `focused_reproducer_or_validation_run` — narrowest possible validation was run",
                '6. **Record** — call `record` with `agent: "atelier:repair"`. Include a postmortem in `learnings`.',
                "",
                "## Hard rules",
                "",
                "- Never retry the same approach a third time. Change strategy or escalate.",
                "- The failing signal must be captured verbatim before calling rescue — vague descriptions produce useless rescues.",
                "- Do not modify unrelated files during repair.",
                "",
                budget_section(),
                "",
                fallback_section("claude"),
            ]
        ).rstrip()
        + "\n"
    )


def render_claude_research_agent(output_path: Path) -> str:
    return (
        "\n".join(
            [
                "---",
                "name: research",
                "description: External researcher. Fetches web pages, GitHub repos, and package docs. Never edits. Produces a structured memo with citations.",
                'tools: ["WebFetch", "WebSearch", "mcp__atelier__context", "mcp__atelier__search", "mcp__atelier__read", "mcp__atelier__memory"]',
                "color: green",
                "---",
                "",
                generated_notice(output_path),
                "",
                "# Atelier Research Agent",
                "",
                "You are the **external researcher**. Fetch, synthesise, and cite. Never edit files.",
                "",
                "## Operating loop",
                "",
                "1. **Context**: Call `context` with `task` and `domain` to surface any codebase-side constraints.",
                "2. **Fetch**: Use `WebFetch` or `WebSearch` for external sources; use `mcp__atelier__search` / `mcp__atelier__read` to cross-reference the codebase.",
                "3. **Synthesise**: Combine findings into a structured memo. Every claim must carry a URL or file:line citation.",
                "4. **Deliver**: Return the memo. Do not wait for tools — partial coverage with citations beats silence.",
                "",
                "## Hard rules",
                "",
                "- **Never edit, write, or delete files.**",
                "- Every factual claim must have a citation (URL or file:line).",
                "- If a source is paywalled or unavailable, say so — do not guess.",
                "- Prefer official docs and source code over blog posts.",
                "",
                "## Output format",
                "",
                "```",
                "## Summary",
                "<2-3 sentence answer>",
                "",
                "## Findings",
                "- <finding> — [source](url)",
                "",
                "## Gaps",
                "- <what could not be confirmed>",
                "```",
                "",
                fallback_section("claude"),
            ]
        ).rstrip()
        + "\n"
    )


def render_cursor_coding_rules() -> str:
    return (
        "\n".join(
            [
                "---",
                "description: Behavioral guidelines to reduce common LLM coding mistakes."
                " Use when writing, reviewing, or refactoring code to avoid overcomplication,"
                " make surgical changes, surface assumptions, and define verifiable success criteria.",
                "alwaysApply: true",
                "---",
                "",
                coding_guidelines_section().strip(),
            ]
        ).rstrip()
        + "\n"
    )


def _antigravity_frontmatter(description: str) -> list[str]:
    return ["---", f"description: {description}", "---", ""]


def render_antigravity_code_agent(output_path: Path) -> str:
    return (
        "\n".join(
            [
                *_antigravity_frontmatter(
                    "Main Atelier coding agent. Uses Atelier MCP tools for all file I/O, search, edits, and shell work."
                ),
                generated_notice(output_path),
                "",
                "# Atelier - Antigravity Plugin Agent",
                "",
                "You are operating as *atelier:code*.",
                "",
                "## Operating loop",
                "",
                "1. **Context**: Call `context` with task, domain, files, tools, and errors when the host supports it.",
                "2. **Implement**: Use Atelier MCP tools for file I/O, search, edits, and shell work."
                " Use native host tools only when Atelier returns `noop`, is hidden, or is unavailable."
                " Use `route` or `rescue` when the same approach fails twice.",
                "3. **Record**: Call `record` when the task is done.",
                "",
                tool_substitution_table(),
                "",
                mcp_priority_section(),
                "",
                budget_section(),
                "",
                coding_guidelines_section(),
                "",
                fallback_section("antigravity"),
                "",
                "## Savings visibility",
                "",
                "Run `atelier status` or `atelier savings --json` to see current savings.",
            ]
        ).rstrip()
        + "\n"
    )


def render_antigravity_explore_agent(output_path: Path) -> str:
    return (
        "\n".join(
            [
                *_antigravity_frontmatter(
                    "Read-only codebase explorer. Finds files, symbols, and patterns. Never edits."
                ),
                generated_notice(output_path),
                "",
                "# Atelier Explore Agent",
                "",
                "You are the **read-only explorer**. Locate, read, and report. Never edit, create, or delete files.",
                "",
                "## Operating loop",
                "",
                "1. **Context**: Call `context` with `task`, `files`, and `domain` to surface relevant ReasonBlocks.",
                "2. **Search**: Prefer `mcp__atelier__search` and `mcp__atelier__read`; use native host tools only as fallback.",
                "3. **Report**: Return findings immediately. Do not wait for tools to become available.",
                "",
                mcp_priority_section(),
                "",
                "## Hard rules",
                "",
                "- **Never edit, write, or delete files.**",
                "- Stay within 12 tool calls per task — prioritize breadth over depth.",
                "- Return findings even when partial — partial coverage beats silence.",
                "- If the first search path is wrong, try an alternative before giving up.",
                "",
                fallback_section("antigravity"),
            ]
        ).rstrip()
        + "\n"
    )


def render_antigravity_repair_agent(output_path: Path) -> str:
    return (
        "\n".join(
            [
                *_antigravity_frontmatter(
                    "Repair specialist for repeated failures."
                    " Captures the failing signal, calls rescue, applies the fix, records a postmortem."
                ),
                generated_notice(output_path),
                "",
                "# Atelier Repair Agent",
                "",
                "You are the **repair specialist**. Activate when the same approach has failed twice.",
                "",
                "## Operating loop",
                "",
                "1. **Capture** the exact failing signal: command output, error text, file and line.",
                "2. **Rescue** — call `rescue` with the error and recent actions. Apply the recommendation exactly.",
                "3. **Validate** — run the narrowest command that would prove the fix worked.",
                "4. **Escalate** — if the same failure persists after the rescue, stop and report. Do not retry a third time.",
                '5. **Record** — call `record` with `agent: "atelier:repair"`. Include a postmortem in `learnings`.',
                "",
                "## Hard rules",
                "",
                "- Never retry the same approach a third time. Change strategy or escalate.",
                "- The failing signal must be captured verbatim before calling rescue.",
                "- Do not modify unrelated files during repair.",
                "",
                budget_section(),
                "",
                fallback_section("antigravity"),
            ]
        ).rstrip()
        + "\n"
    )


def render_antigravity_research_agent(output_path: Path) -> str:
    return (
        "\n".join(
            [
                *_antigravity_frontmatter(
                    "External researcher. Fetches web pages, GitHub repos, and package docs."
                    " Never edits. Produces a structured memo with citations."
                ),
                generated_notice(output_path),
                "",
                "# Atelier Research Agent",
                "",
                "You are the **external researcher**. Fetch, synthesise, and cite. Never edit files.",
                "",
                "## Operating loop",
                "",
                "1. **Context**: Call `context` with `task` and `domain` to surface any codebase-side constraints.",
                "2. **Fetch**: Use web tools for external sources; use `mcp__atelier__search` / `mcp__atelier__read` to cross-reference the codebase.",
                "3. **Synthesise**: Combine findings into a structured memo. Every claim must carry a URL or file:line citation.",
                "4. **Deliver**: Return the memo. Do not wait for tools — partial coverage with citations beats silence.",
                "",
                "## Hard rules",
                "",
                "- **Never edit, write, or delete files.**",
                "- Every factual claim must have a citation (URL or file:line).",
                "- If a source is paywalled or unavailable, say so — do not guess.",
                "- Prefer official docs and source code over blog posts.",
                "",
                "## Output format",
                "",
                "```",
                "## Summary",
                "<2-3 sentence answer>",
                "",
                "## Findings",
                "- <finding> — [source](url)",
                "",
                "## Gaps",
                "- <what could not be confirmed>",
                "```",
                "",
                fallback_section("antigravity"),
            ]
        ).rstrip()
        + "\n"
    )


def render_antigravity_review_agent(output_path: Path) -> str:
    return (
        "\n".join(
            [
                *_antigravity_frontmatter(
                    "Adversarial code reviewer. Applies the verification ladder. Never edits source files."
                ),
                generated_notice(output_path),
                "",
                "# Atelier Review Agent",
                "",
                "You are the **adversarial reviewer**. Your job is to find what is wrong, not to validate that work was done.",
                "",
                "## Operating loop",
                "",
                "1. **Read** the files in scope, preferring `mcp__atelier__read` and `mcp__atelier__search` before native host tools. Never trust summaries — verify the code directly.",
                "2. **Apply the verification ladder**: existence → substantive → wired → data flow.",
                "3. **Report findings**: every finding must have a severity (Blocker|Warning), `file:line`, and a concrete fix.",
                '4. **Record** — call `record` with `agent: "atelier:review"`. Include learnings for any surprise or lesson.',
                "",
                "## Hard rules",
                "",
                "- **Never edit source files.** Read only.",
                "- Every finding must carry Blocker or Warning. Unlabelled findings are invalid output.",
                "- Every Blocker must include `file:line` and a concrete fix snippet.",
                "- Do not flag style preferences as Blocker or Warning.",
                "- `status: skipped` (nothing to review) ≠ `status: clean` (reviewed, no issues).",
                "",
                fallback_section("antigravity"),
            ]
        ).rstrip()
        + "\n"
    )


def _opencode_frontmatter(description: str) -> list[str]:
    return ["---", f"description: {description}", "---", ""]


def render_opencode_explore_agent(output_path: Path) -> str:
    return (
        "\n".join(
            [
                *_opencode_frontmatter("Read-only codebase explorer. Finds files, symbols, and patterns. Never edits."),
                generated_notice(output_path),
                "",
                "# Atelier Explore Agent",
                "",
                "You are the **read-only explorer**. Locate, read, and report. Never edit, create, or delete files.",
                "",
                "## Operating loop",
                "",
                "1. **Context**: Call `context` with `task`, `files`, and `domain` to surface relevant ReasonBlocks.",
                "2. **Search**: Prefer `mcp__atelier__search` and `mcp__atelier__read`; use native host tools only as fallback.",
                "3. **Report**: Return findings immediately. Do not wait for tools to become available.",
                "",
                mcp_priority_section(),
                "",
                "## Hard rules",
                "",
                "- **Never edit, write, or delete files.**",
                "- Stay within 12 tool calls per task — prioritize breadth over depth.",
                "- Return findings even when partial — partial coverage beats silence.",
                "- If the first search path is wrong, try an alternative before giving up.",
                "",
                fallback_section("opencode"),
            ]
        ).rstrip()
        + "\n"
    )


def render_opencode_repair_agent(output_path: Path) -> str:
    return (
        "\n".join(
            [
                *_opencode_frontmatter(
                    "Repair specialist for repeated failures."
                    " Captures the failing signal, calls rescue, applies the fix, records a postmortem."
                ),
                generated_notice(output_path),
                "",
                "# Atelier Repair Agent",
                "",
                "You are the **repair specialist**. Activate when the same approach has failed twice.",
                "",
                "## Operating loop",
                "",
                "1. **Capture** the exact failing signal: command output, error text, file and line.",
                "2. **Rescue** — call `rescue` with the error and recent actions. Apply the recommendation exactly.",
                "3. **Validate** — run the narrowest command that would prove the fix worked.",
                "4. **Escalate** — if the same failure persists after the rescue, stop and report. Do not retry a third time.",
                '5. **Record** — call `record` with `agent: "atelier:repair"`. Include a postmortem in `learnings`.',
                "",
                "## Hard rules",
                "",
                "- Never retry the same approach a third time. Change strategy or escalate.",
                "- The failing signal must be captured verbatim before calling rescue.",
                "- Do not modify unrelated files during repair.",
                "",
                budget_section(),
                "",
                fallback_section("opencode"),
            ]
        ).rstrip()
        + "\n"
    )


def render_opencode_research_agent(output_path: Path) -> str:
    return (
        "\n".join(
            [
                *_opencode_frontmatter(
                    "External researcher. Fetches web pages, GitHub repos, and package docs."
                    " Never edits. Produces a structured memo with citations."
                ),
                generated_notice(output_path),
                "",
                "# Atelier Research Agent",
                "",
                "You are the **external researcher**. Fetch, synthesise, and cite. Never edit files.",
                "",
                "## Operating loop",
                "",
                "1. **Context**: Call `context` with `task` and `domain` to surface any codebase-side constraints.",
                "2. **Fetch**: Use web tools for external sources; use `mcp__atelier__search` / `mcp__atelier__read` to cross-reference the codebase.",
                "3. **Synthesise**: Combine findings into a structured memo. Every claim must carry a URL or file:line citation.",
                "4. **Deliver**: Return the memo. Do not wait for tools — partial coverage with citations beats silence.",
                "",
                "## Hard rules",
                "",
                "- **Never edit, write, or delete files.**",
                "- Every factual claim must have a citation (URL or file:line).",
                "- If a source is paywalled or unavailable, say so — do not guess.",
                "- Prefer official docs and source code over blog posts.",
                "",
                "## Output format",
                "",
                "```",
                "## Summary",
                "<2-3 sentence answer>",
                "",
                "## Findings",
                "- <finding> — [source](url)",
                "",
                "## Gaps",
                "- <what could not be confirmed>",
                "```",
                "",
                fallback_section("opencode"),
            ]
        ).rstrip()
        + "\n"
    )


def render_opencode_review_agent(output_path: Path) -> str:
    return (
        "\n".join(
            [
                *_opencode_frontmatter(
                    "Adversarial code reviewer. Applies the verification ladder. Never edits source files."
                ),
                generated_notice(output_path),
                "",
                "# Atelier Review Agent",
                "",
                "You are the **adversarial reviewer**. Your job is to find what is wrong, not to validate that work was done.",
                "",
                "## Operating loop",
                "",
                "1. **Read** the files in scope, preferring `mcp__atelier__read` and `mcp__atelier__search` before native host tools. Never trust summaries — verify the code directly.",
                "2. **Apply the verification ladder**: existence → substantive → wired → data flow.",
                "3. **Report findings**: every finding must have a severity (Blocker|Warning), `file:line`, and a concrete fix.",
                '4. **Record** — call `record` with `agent: "atelier:review"`. Include learnings for any surprise or lesson.',
                "",
                "## Hard rules",
                "",
                "- **Never edit source files.** Read only.",
                "- Every finding must carry Blocker or Warning. Unlabelled findings are invalid output.",
                "- Every Blocker must include `file:line` and a concrete fix snippet.",
                "- Do not flag style preferences as Blocker or Warning.",
                "- `status: skipped` (nothing to review) ≠ `status: clean` (reviewed, no issues).",
                "",
                fallback_section("opencode"),
            ]
        ).rstrip()
        + "\n"
    )


def render_host_surface(output_path: Path, *, title: str, host: str) -> str:
    lines = [
        generated_notice(output_path),
        "",
        f"# {title}",
        "",
        "You are operating as *atelier:code*.",
        "",
        "## Operating loop",
        "",
        "1. **Context**: Call `context` with task, domain, files, tools, and errors when the host supports it.",
        "2. **Implement**: Use Atelier MCP tools for file I/O, search, edits, and shell work."
        " Use native host tools only when Atelier returns `noop`, is hidden, or is unavailable."
        " Use `route` or `rescue` when the same approach fails twice.",
        "3. **Record**: Call `record` when the task is done.",
        "",
        tool_substitution_table(),
        "",
        mcp_priority_section(),
        "",
        budget_section(),
        "",
        coding_guidelines_section(),
        "",
        fallback_section(host),
        "",
        "## Savings visibility",
        "",
        "Run `atelier status` or `atelier savings --json` to see current savings.",
    ]
    if host == "opencode":
        return (
            "\n".join(
                [
                    "---",
                    "description: Atelier - main coding agent for the Agent Reasoning Runtime",
                    "mode: primary",
                    "---",
                    "",
                    *lines,
                ]
            ).rstrip()
            + "\n"
        )
    return "\n".join(lines).rstrip() + "\n"


def sync_host_configs() -> dict[Path, str]:
    outputs: dict[Path, str] = {}
    for host in ("claude", "codex", "copilot", "antigravity", "opencode", "cursor", "hermes"):
        path = ROOT / "src/atelier/gateway/hosts/configs" / f"{host}.yaml"
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
        templates = data.get("prompt_templates", [])
        for item in templates:
            if item.get("name") == "session-optimization":
                item["template"] = SESSION_TEMPLATE.format(host=HOST_DISPLAY[host]).rstrip()
        outputs[path] = yaml.safe_dump(data, sort_keys=False, allow_unicode=False)
    return outputs


def build_outputs() -> dict[Path, str]:
    outputs = {
        ROOT / "AGENTS.md": render_project_entrypoint(ROOT / "AGENTS.md", title="Project Instructions: Atelier"),
        ROOT / ".github/copilot-instructions.md": render_copilot_workspace(ROOT / ".github/copilot-instructions.md"),
        ROOT / ".github/chatmodes/atelier.chatmode.md": render_chatmode(ROOT / ".github/chatmodes/atelier.chatmode.md"),
        ROOT
        / "integrations/copilot/COPILOT_INSTRUCTIONS.atelier.md": render_copilot_user_surface(
            ROOT / "integrations/copilot/COPILOT_INSTRUCTIONS.atelier.md"
        ),
        ROOT
        / "integrations/copilot/chatmodes/atelier.chatmode.md": render_chatmode(
            ROOT / "integrations/copilot/chatmodes/atelier.chatmode.md"
        ),
        ROOT
        / "integrations/claude/AGENTS.atelier.md": render_host_surface(
            ROOT / "integrations/claude/AGENTS.atelier.md",
            title="Atelier Agent Persona",
            host="claude",
        ),
        ROOT
        / "integrations/claude/plugin/agents/code.md": render_claude_code_agent(
            ROOT / "integrations/claude/plugin/agents/code.md"
        ),
        ROOT
        / "integrations/claude/plugin/agents/review.md": render_claude_review_agent(
            ROOT / "integrations/claude/plugin/agents/review.md"
        ),
        ROOT
        / "integrations/claude/plugin/agents/explore.md": render_claude_explore_agent(
            ROOT / "integrations/claude/plugin/agents/explore.md"
        ),
        ROOT
        / "integrations/claude/plugin/agents/repair.md": render_claude_repair_agent(
            ROOT / "integrations/claude/plugin/agents/repair.md"
        ),
        ROOT
        / "integrations/claude/plugin/agents/research.md": render_claude_research_agent(
            ROOT / "integrations/claude/plugin/agents/research.md"
        ),
        ROOT
        / "integrations/codex/AGENTS.atelier.md": render_host_surface(
            ROOT / "integrations/codex/AGENTS.atelier.md",
            title="Atelier - Codex Agent",
            host="codex",
        ),
        ROOT
        / "integrations/antigravity/AGENTS.atelier.md": render_host_surface(
            ROOT / "integrations/antigravity/AGENTS.atelier.md",
            title="Atelier - Antigravity Agent",
            host="antigravity",
        ),
        ROOT
        / "integrations/antigravity/plugin/agents/atelier-code.md": render_antigravity_code_agent(
            ROOT / "integrations/antigravity/plugin/agents/atelier-code.md"
        ),
        ROOT
        / "integrations/antigravity/plugin/agents/atelier-explore.md": render_antigravity_explore_agent(
            ROOT / "integrations/antigravity/plugin/agents/atelier-explore.md"
        ),
        ROOT
        / "integrations/antigravity/plugin/agents/atelier-repair.md": render_antigravity_repair_agent(
            ROOT / "integrations/antigravity/plugin/agents/atelier-repair.md"
        ),
        ROOT
        / "integrations/antigravity/plugin/agents/atelier-research.md": render_antigravity_research_agent(
            ROOT / "integrations/antigravity/plugin/agents/atelier-research.md"
        ),
        ROOT
        / "integrations/antigravity/plugin/agents/atelier-review.md": render_antigravity_review_agent(
            ROOT / "integrations/antigravity/plugin/agents/atelier-review.md"
        ),
        ROOT
        / "integrations/opencode/agents/atelier.md": render_host_surface(
            ROOT / "integrations/opencode/agents/atelier.md",
            title="atelier:code",
            host="opencode",
        ),
        ROOT
        / "integrations/opencode/agents/explore.md": render_opencode_explore_agent(
            ROOT / "integrations/opencode/agents/explore.md"
        ),
        ROOT
        / "integrations/opencode/agents/repair.md": render_opencode_repair_agent(
            ROOT / "integrations/opencode/agents/repair.md"
        ),
        ROOT
        / "integrations/opencode/agents/research.md": render_opencode_research_agent(
            ROOT / "integrations/opencode/agents/research.md"
        ),
        ROOT
        / "integrations/opencode/agents/review.md": render_opencode_review_agent(
            ROOT / "integrations/opencode/agents/review.md"
        ),
        ROOT
        / "integrations/cursor/AGENTS.atelier.md": render_host_surface(
            ROOT / "integrations/cursor/AGENTS.atelier.md",
            title="Atelier - Cursor Agent",
            host="cursor",
        ),
        ROOT / "integrations/cursor/rules/coding-guidelines.mdc": render_cursor_coding_rules(),
        ROOT
        / "integrations/hermes/AGENTS.atelier.md": render_host_surface(
            ROOT / "integrations/hermes/AGENTS.atelier.md",
            title="Atelier - Hermes Agent",
            host="hermes",
        ),
    }
    outputs.update(build_mode_outputs(ROOT))
    outputs.update(sync_host_configs())
    return outputs


def write_or_diff(path: Path, expected: str, *, check: bool) -> bool:
    current = path.read_text(encoding="utf-8") if path.exists() else ""
    if current == expected:
        return False
    if check:
        diff = difflib.unified_diff(
            current.splitlines(),
            expected.splitlines(),
            fromfile=str(path),
            tofile=f"{path} (generated)",
            lineterm="",
        )
        sys.stdout.write("\n".join(diff) + "\n")
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(expected, encoding="utf-8")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated files differ from checked-in copies")
    args = parser.parse_args()

    changed = False
    for path, content in build_outputs().items():
        changed = write_or_diff(path, content, check=args.check) or changed

    if args.check and changed:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
